# Generated by Django 3.2.11 on 2024-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_remove_organization_msgraph_write_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onedrive_delete_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of online drive files directly'),
        ),
    ]
