# Generated by Django 3.2.11 on 2024-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0133_rulecategory_model_and_population'),
        ('organizations', '0041_alias_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='system_rules',
            field=models.ManyToManyField(related_name='organizations', to='os2datascanner.CustomRule', verbose_name='system rules'),
        ),
    ]
