# Generated by Django 4.0.10 on 2024-07-11 06:47

import django.core.validators
from django.db import migrations
import os2datascanner.projects.admin.organizations.models.organization


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0041_alias_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='synchronization_hour',
            field=os2datascanner.projects.admin.organizations.models.organization.HourField(default=17, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)], verbose_name='synchronization hour'),
        ),
    ]
