# Generated by Django 3.2.11 on 2024-08-09 07:24

from django.db import migrations
import os2datascanner.projects.admin.organizations.models.organization


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0042_organization_system_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='synchronization_time',
            field=os2datascanner.projects.admin.organizations.models.organization.HourField(default='17:00', verbose_name='synchronization time'),
        ),
    ]
