# Generated by Django 3.2.11 on 2024-09-10 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0043_organization_synchronization_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='dtstart',
            field=models.DateField(default=datetime.date.today, verbose_name='schedule start time'),
        ),
    ]
