# Generated by Django 3.2.11 on 2024-09-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0044_organization_dtstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='dpo_contact_method',
            field=models.CharField(choices=[('NO', 'None'), ('SD', 'Single DPO'), ('UD', 'Unit DPO')], default='NO', max_length=2, verbose_name='DPO contact method'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='support_contact_method',
            field=models.CharField(choices=[('NO', 'None'), ('WS', 'Website'), ('EM', 'Email')], default='NO', max_length=2, verbose_name='support contact method'),
        ),
    ]
