# Generated by Django 3.2.11 on 2024-11-26 13:56

from django.db import migrations, models
import os2datascanner.core_organizational_structure.models.account


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0048_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permissions',
            field=models.JSONField(default=list, validators=[os2datascanner.core_organizational_structure.models.account.validate_list_of_enum_vals], verbose_name='Account permissions'),
        ),
    ]
