# Generated by Django 3.2.11 on 2024-12-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_organizationalunit_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={'permissions': [('change_visibility_organizationalunit', 'Can change visibility of organizational units')], 'verbose_name': 'organizational unit', 'verbose_name_plural': 'organizational units'},
        ),
    ]
