# Generated by Django 3.2.11 on 2024-11-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0050_account_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('can_give_permissions', 'Can grant permission to users in the report module'), ('can_take_permissions', 'Can take permissions away from users in the report module')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
    ]
