# Generated by Django 3.2.11 on 2025-03-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0051_organization_retention_policy_and_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('test_permission', 'This is a test permission. It does not grant access to anything.')],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('change_permissions_account', 'Can grant and take away permissions to and from users in the report module')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AddField(
            model_name='account',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'content_type__model': 'syncedpermission'}, to='auth.Permission', verbose_name='account permissions'),
        ),
    ]
