# Generated by Django 3.2.11 on 2025-04-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0055_organization_sbsystab_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncedpermission',
            options={'permissions': [('view_sbsys_tab', 'Can view the SBSYS tab in Report')]},
        ),
    ]
