# Generated by Django 3.2.11 on 2025-05-05 12:29

from django.db import migrations, models
import os2datascanner.core_organizational_structure.utils


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0056_alter_syncedpermission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, validators=[os2datascanner.core_organizational_structure.utils.validate_mail], verbose_name='contact email'),
        ),
    ]
