# Generated by Django 3.2.11 on 2025-05-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0057_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='shared',
            field=models.BooleanField(default=False, help_text='The results related to the user through this alias is shared with other users. Matches associated through this alias will not be taken into account in user statistics, except for in email notifications.', verbose_name='shared'),
        ),
    ]
