# Generated by Django 5.2.1 on 2025-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0061_organization_leadertab_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='exchange_delete_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of emails on Exchange server directly'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='gdrive_delete_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of files in Google Drive directly'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='gmail_delete_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of emails in gmail directly'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='onedrive_delete_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of online drive files directly'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='outlook_delete_email_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of emails in Outlook directly'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='smb_delete_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of on-premise drive files directly'),
        ),
    ]
