# Generated by Django 5.2.1 on 2025-08-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0020_grant_inherit_link'),
        ('organizations', '0062_alter_organization_exchange_delete_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_broadcast', models.BooleanField(default=False, verbose_name='Should Broadcast')),
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant_extra', to='grants.grant', verbose_name='Grant Extra')),
            ],
        ),
    ]
