# Generated by Django 5.2.1 on 2025-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0064_alter_syncedpermission_options'),
        ('os2datascanner', '0169_prep_for_rule_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='system_rules',
            field=models.ManyToManyField(related_name='organizations', to='os2datascanner.rule', verbose_name='system rules'),
        ),
    ]
