# Generated by Django 5.2.1 on 2025-10-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0065_alter_organization_system_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncedpermission',
            options={'permissions': [('view_sbsys_tab', 'Can view the SBSYS tab in the report module'), ('filter_scannerjob_leader_overview', 'Can filter by scannerjob in the leader overview'), ('view_withheld_results', 'Can view the withheld results tab in the report module'), ('handle_withheld_results', 'Can handle withheld results in the report module'), ('distribute_withheld_results', 'Can distribute withheld results to users in the report module')]},
        ),
    ]
