# Generated by Django 5.2.1 on 2025-11-11 13:27

from django.db import migrations, models
from os2datascanner.utils.ldap import RDN


def move_ldap_distinguished_names(apps, schema_editor):
    Account = apps.get_model('organizations', 'Account')

    for account in Account.objects.iterator():
        if RDN.valid_dn(account.imported_id):
            account.distinguished_name = account.imported_id
            account.imported_id = None
            account.save()


def reverse(apps, schema_editor):
    Account = apps.get_model('organizations', 'Account')

    for account in Account.objects.iterator():
        if account.distinguished_name:
            account.imported_id = account.distinguished_name
            account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0067_alter_syncedpermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='distinguished_name',
            field=models.TextField(blank=True, null=True, verbose_name='imported LDAP distinguished name'),
        ),
        migrations.RunPython(move_ldap_distinguished_names, reverse_code=reverse),
    ]
