# Generated by Django 5.2.1 on 2026-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0068_account_distinguished_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='outlook_categorize_email_permission',
            field=models.CharField(choices=[('ORG', 'Automatic categorization for everyone'), ('IND', 'Individual users manage categorization'), ('NON', 'Categorization disabled')], default='NON', help_text='Choose whether matched emails are automatically categorized for the entire organization, categorized individually by users, or not categorized at all.', max_length=3, verbose_name='Outlook category settings'),
        ),
    ]
