# Generated by Django 5.2.1 on 2026-03-27 10:57

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.apps.registry import Apps


def fix_permission_name(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    synced_perm_ct = ContentType.objects.get(
            app_label="organizations",
            model="syncedpermission")

    perm = Permission.objects.filter(
            content_type=synced_perm_ct, codename="view_sbsys_tab")
    perm.update(name="Can view the SBSYS tab in the report module")



class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0069_alter_organization_outlook_categorize_email_permission'),
    ]

    operations = [
        migrations.RunPython(
                fix_permission_name, reverse_code=migrations.RunPython.noop),
    ]
