# Generated by Django 5.2.1 on 2026-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0070_unbreak_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='_alias_type',
            field=models.CharField(choices=[('SID', 'SID'), ('email', 'email'), ('remediator', 'remediator'), ('upn', 'user principal name'), ('generic', 'generic'), ('logon', 'Windows logon name')], db_column='alias_type', db_index=True, max_length=32, verbose_name='alias type'),
        ),
    ]
