# Generated by Django 5.2.1 on 2026-06-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0072_organization_leader_snapshot_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='level',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organizationalunit', verbose_name='parent unit'),
        ),
        migrations.AlterField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organizations.organizationalunit', verbose_name='organizational unit'),
        ),
    ]
