# Generated by Django 5.2.1 on 2026-09-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0073_remove_organizationalunit_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='exchange_calendar_delete_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of calendar events on Exchange server directly'),
        ),
    ]
