# Generated by Django 3.2.11 on 2024-05-15 14:54

import uuid

from django.db import migrations, models
from django.conf import settings

from os2datascanner.utils.batch import BatchUpdate
from os2datascanner.projects.utils import aes


def populate_graphgrant_fields(apps, schema_editor):
    GraphGrant = apps.get_model("grants", "GraphGrant")

    with BatchUpdate(
            GraphGrant.objects, ["app_id", "_client_secret"]) as batch:
        for obj in GraphGrant.objects.iterator():
            obj.app_id = settings.MSGRAPH_APP_ID

            iv, ciphertext = aes.encrypt(
                    settings.MSGRAPH_CLIENT_SECRET, settings.DECRYPTION_HEX)
            obj._client_secret = [c.hex() for c in (iv, ciphertext)]

            batch.append(obj)


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphgrant',
            name='app_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='app ID'),
        ),

        migrations.AddField(
            model_name='graphgrant',
            name='_client_secret',
            field=models.JSONField(null=True, verbose_name='client secret'),
        ),
        migrations.RunPython(
            code=populate_graphgrant_fields,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='graphgrant',
            name='_client_secret',
            field=models.JSONField(verbose_name='client secret'),
        ),
    ]
