# Generated by Django 3.2.11 on 2024-05-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('grants', '0002_graphgrant_complexify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphgrant', related_query_name='graphgrants', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='SMBGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='username')),
                ('_password', models.JSONField(verbose_name='password (encrypted)')),
                ('domain', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smbgrant', related_query_name='smbgrants', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='smbgrant',
            constraint=models.UniqueConstraint(fields=('organization', 'domain', 'username'), name='grants_smbgrant_unique'),
        ),
    ]
