# Generated by Django 3.2.11 on 2024-05-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('grants', '0003_smbgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWSGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='username')),
                ('_password', models.JSONField(verbose_name='password (encrypted)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ewsgrant', related_query_name='ewsgrants', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='ewsgrant',
            constraint=models.UniqueConstraint(fields=('organization', 'username'), name='grants_ewsgrant_unique'),
        ),
    ]
