# Generated by Django 3.2.11 on 2024-06-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    # The grants app's initial migration depends on organizations/0001_initial
    # in an attempt to find a named migration that exists in both the admin
    # system and the report module. This was very nearly a good idea, but
    # organizations/0001_initial in the report module is a disaster on wheels:
    # it defines a concrete object with no database relation and with the
    # wrong sort of primary key! To fix that, an out-of-sequence dummy
    # migration 0040 has been added to both halves of the system; this third
    # dummy migration forces the grants app back in sync

    dependencies = [
        ('grants', '0004_ewsgrant'),
        ('organizations', '0040_dummy_sync'),
    ]

    operations = [
    ]
