# Generated by Django 3.2.11 on 2024-06-12 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_dummy_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphgrant',
            name='app_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='app ID'),
        ),
        migrations.AlterField(
            model_name='graphgrant',
            name='tenant_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='tenant ID'),
        ),
    ]
