# Generated by Django 4.0.10 on 2024-06-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0040_dummy_sync'),
        ('grants', '0006_editability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewsgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', related_query_name='%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='graphgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', related_query_name='%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='smbgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', related_query_name='%(class)ss', to='organizations.organization'),
        ),
    ]
