# Generated by Django 3.2.11 on 2024-10-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_alter_ewsgrant_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphgrant',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiry date'),
        ),
    ]
