# Generated by Django 3.2.11 on 2025-02-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0009_set_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ewsgrant',
            options={'verbose_name': 'EWS Service Account'},
        ),
        migrations.AlterModelOptions(
            name='graphgrant',
            options={'verbose_name': 'Microsoft Graph'},
        ),
        migrations.AlterModelOptions(
            name='smbgrant',
            options={'verbose_name': 'SMB Service Account'},
        ),
    ]
