# Generated by Django 3.2.11 on 2025-03-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0051_organization_retention_policy_and_value'),
        ('grants', '0010_alter_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewsgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ewsgrant', related_query_name='ewsgrants', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='graphgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphgrant', related_query_name='graphgrants', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='smbgrant',
            name='domain',
            field=models.TextField(blank=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='smbgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smbgrant', related_query_name='smbgrants', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
