# Generated by Django 3.2.11 on 2025-03-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0051_organization_retention_policy_and_value'),
        ('grants', '0011_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleApiGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_service_account', models.JSONField(null=True, verbose_name='Service account json')),
                ('account_name', models.CharField(max_length=256, verbose_name='Service Account Name')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiration date')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googleapigrant', related_query_name='googleapigrants', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Google Api Grant',
            },
        ),
        migrations.AddConstraint(
            model_name='googleapigrant',
            constraint=models.UniqueConstraint(fields=('organization', 'account_name'), name='avoid_duplicate_grants'),
        ),
    ]
