# Generated by Django 3.2.11 on 2025-03-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0011_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleApiGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('_service_account', models.JSONField(null=True, verbose_name='Service account json')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googleapigrant', related_query_name='googleapigrants', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Google Api Grant',
            },
        ),
    ]
