# Generated by Django 3.2.11 on 2025-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0012_googleapigrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewsgrant',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='graphgrant',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='smbgrant',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='googleapigrant',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
    ]
