# Generated by Django 4.2.21 on 2025-05-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0058_alter_alias_shared'),
        ('grants', '0013_add_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewsgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', related_query_name='%(class)ss', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='googleapigrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', related_query_name='%(class)ss', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='graphgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', related_query_name='%(class)ss', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='smbgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', related_query_name='%(class)ss', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
