# Generated by Django 5.2.1 on 2025-07-15 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0014_alter_ewsgrant_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewsgrant',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='googleapigrant',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='graphgrant',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='smbgrant',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='UUID'),
        ),
    ]
