# Generated by Django 5.2.1 on 2025-07-15 14:14

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    EWSGrant = apps.get_model("grants", "EWSGrant")
    GoogleApiGrant = apps.get_model("grants", "GoogleApiGrant")
    GraphGrant = apps.get_model("grants", "GraphGrant")
    SMBGrant = apps.get_model("grants", "SMBGrant")

    grants = [EWSGrant, GoogleApiGrant, GraphGrant, SMBGrant]

    for grant_type in grants:
        for grant in grant_type.objects.all():
            grant.uuid = uuid.uuid4()
            grant.save(update_fields=["uuid"])



class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0015_ewsgrant_uuid_googleapigrant_uuid_graphgrant_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
