# Generated by Django 5.2.1 on 2025-07-15 14:14

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0016_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewsgrant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                   verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='googleapigrant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                   verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='graphgrant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                   verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='smbgrant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                   verbose_name='UUID'),
        ),
    ]
