# Generated by Django 5.2.1 on 2025-07-15 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0017_set_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewsgrant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='googleapigrant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='graphgrant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='smbgrant',
            name='id',
        ),
        migrations.AlterField(
            model_name='ewsgrant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='googleapigrant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='graphgrant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='smbgrant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
