# Generated by Django 5.2.1 on 2025-11-17 13:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0020_grant_inherit_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graphgrant',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact_for_grant', to=settings.AUTH_USER_MODEL, verbose_name='contacts'),
        ),
        migrations.AddField(
            model_name='graphgrant',
            name='last_email_date',
            field=models.DateField(default=datetime.date.today, verbose_name='last email date'),
        ),
    ]
