SECRET_KEY = "DUMMYKEY(for development)DUMMYKEY(for development)"
DECRYPTION_HEX = "4b8930847cba7196a46ede3456fe33df564427a30910dd1ef9bc805f26559aeb"

MEDIA_ROOT = ["*"," src", "os2datascanner", "projects", "report"]

# [mode]
DEBUG = true
KEYCLOAK_ENABLED = true

# [logging]
LOG_LEVEL = "INFO"

# [functionality]
HANDLE_DROPDOWN = true
ALLOW_CONTACT_MAGENTA = true
DPO_CSV_EXPORT = true
LEADER_CSV_EXPORT = true
ALLOW_SHOW_ERRORS = true
HYBRID_LOGIN = true

# [site]
# The URL of this site, used in links in emails and in the redirect URL for
# OAuth 2.0 services. (This value should end with a forward slash.)
SITE_URL = "http://localhost:8040/"
ALLOWED_HOSTS = []
SESSION_COOKIE_NAME = "report_sessionid"

# [installation]
OPTIONAL_APPS = [
    'debug_toolbar',
]
OPTIONAL_MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# The name of the institution, to be included in the notification signoff
NOTIFICATION_INSTITUTION = 'MAGENTA APS'

# [msgraph]
MSGRAPH_APP_ID = ""
MSGRAPH_CLIENT_SECRET = ""
MSGRAPH_TENANT_ID = ""

# KEYCLOAK
# These settings require a os2datascanner client, and a osdatascanner realm in Keycloak.
# endpoints
OIDC_OP_AUTHORIZATION_ENDPOINT = "http://localhost:8090/auth/realms/osdatascanner/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "http://localhost:8090/auth/realms/osdatascanner/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "http://localhost:8090/auth/realms/osdatascanner/protocol/openid-connect/userinfo"
# signing algorithm and key
OIDC_OP_JWKS_ENDPOINT = "http://localhost:8090/auth/realms/osdatascanner/protocol/openid-connect/certs"
# login and logout urls
LOGOUT_URL = "http://localhost:8090/auth/realms/osdatascanner/protocol/openid-connect/logout"


# Redirect urls
LOGIN_REDIRECT_URL = "http://localhost:8040/"

# [email]
DEFAULT_FROM_EMAIL = "os2datascanner@magenta.dk"
ADMIN_EMAIL = "os2datascanner@magenta.dk"
EMAIL_HOST = 'mailhog'
EMAIL_PORT = 1025

# options for django_debug_toolbar,
# https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#debug-toolbar-config
[DEBUG_TOOLBAR_CONFIG]
SHOW_COLLAPSED = true
SHOW_TOOLBAR_CALLBACK = "os2datascanner.projects.utils.debug.debug_toolbar_callback"

[DATABASES]

    [DATABASES.default]
    ENGINE = "django_prometheus.db.backends.postgresql"
    NAME = "os2datascanner_report"
    USER = "os2datascanner_report_dev"
    PASSWORD = "os2datascanner_report_dev"
    HOST = "db"

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "queue"
AMQP_USER = "os2ds"
AMQP_PWD = "os2ds"
