SECRET_KEY = "DUMMYKEY(for testing)DUMMYKEY(for testing)"
DECRYPTION_HEX = "4b8930847cba7196a46ede3456fe33df564427a30910dd1ef9bc805f26559aeb"

[DATABASES]

    [DATABASES.default]
    ENGINE = "django.db.backends.postgresql_psycopg2"
    NAME = "os2datascanner"
    USER = "os2datascanner"
    PASSWORD = "os2datascanner"
    HOST = "postgres"

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "rabbitmq"
AMQP_USER = "guest"
AMQP_PWD = "guest"
