# For the release steps to work, the following environment variables have to set
# in the Gitlab UI:
# RELEASE_REGISTRY_USER
# RELEASE_REGISTRY_PASSWORD

# Saltbert, used for automatic deployment of our test server
include:
  - project: labs/salt-automation
    file:
      - /gitlab-ci-templates/common/saltbert.v1.yml
      - gitlab-ci-templates/common/docker-build-meta.v2.yml
  - helpers/document-proxy/.gitlab-ci.yml

stages:
  - lint
  - pre-build
  - build
  - test
  - release
  - deploy


variables:
  # Project variables
  RELEASE_REGISTRY: docker.io
  RELEASE_REPORT_IMAGE: index.docker.io/magentaaps/os2datascanner-report
  RELEASE_ADMIN_IMAGE: index.docker.io/magentaaps/os2datascanner-admin
  RELEASE_ENGINE_IMAGE: index.docker.io/magentaaps/os2datascanner-engine
  RELEASE_API_IMAGE: index.docker.io/magentaaps/os2datascanner-api

  BASE_IMAGE: ${CI_REGISTRY_IMAGE}/base:${CI_COMMIT_SHA}
  REPORT_IMAGE: ${CI_REGISTRY_IMAGE}/report:${CI_COMMIT_SHA}
  ADMIN_IMAGE: ${CI_REGISTRY_IMAGE}/admin:${CI_COMMIT_SHA}
  ENGINE_IMAGE: ${CI_REGISTRY_IMAGE}/engine:${CI_COMMIT_SHA}
  API_IMAGE: ${CI_REGISTRY_IMAGE}/api:${CI_COMMIT_SHA}
  DOCKERFILE: ${CI_PROJECT_DIR}/docker/base/Dockerfile
