repos:
-   repo: https://github.com/hhatto/autopep8
    rev: 'v2.3.1'
    hooks:
    - id: autopep8
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      entry: pflake8 src
      additional_dependencies: [pyproject-flake8, flake8-cognitive-complexity, flake8-expression-complexity, flake8-bugbear==22.12.6]
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: 'v2.13.0'
    hooks:
    -   id: jshint
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: 'v1.25.0'
    hooks:
    -   id: djlint-django
        name: djlint
        entry: djlint --reformat --indent 2 --preserve-blank-lines --quiet
        files: src/os2datascanner/projects/
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
    -   id: prettier
        types: [scss]