repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'
    hooks:
    - id: autopep8
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.259'
    hooks:
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: 'v2.13.0'
    hooks:
    -   id: jshint
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: 'v1.19.8'
    hooks:
    -   id: djlint-django
        name: djlint
        entry: djlint --reformat --quiet
        files: src/os2datascanner/projects/