site_name: OSdatascanner Docs
site_url: https://os2datascanner.rtfd.io

theme: readthedocs

markdown_extensions:
  - footnotes
  - sane_lists
  - admonition

nav:
  - Overview: index.md
  - Data Sources: data-sources.md
  - Management Commands: management-commands.md
  - Development Environment:
    - The Basics: development_environment/the-basics.md
    - Docker Compose: development_environment/docker-compose.md
    - Quickstart Scannables: development_environment/quickstart_dev_scannables.md
    - Connecting to Host: development_environment/connecting_to_host.md
    - Translations: development_environment/translations.md
    - Missing Permissions: development_environment/missing-permissions.md
    - Hooks and Linting: development_environment/hooks_and_lint.md
    - Run Tests: development_environment/tests.md
    - Debugging: development_environment/debugging.md
    - Keycloak/LDAP: development_environment/keycloak_ldap.md
    - O365 Scan Prerequisites: development_environment/O365_scan_prerequisites.md
    - OS2mo Import job: development_environment/OS2mo_import.md
  - The engine:
    - Engine/pipeline: architecture/pipeline.md
    - Engine/RabbitMQ: architecture/rabbitmq.md
    - The model: engine2.md
    - The rule engine: rules.md
    - Pre-execution of rules (SmartDelta): smartdelta.md
    - Scanner settings: scanner-settings.md
    - Direct database scan: ddb.md
  - Security Architecture: architecture/security.md
  - Scan API: api.md
  - Accessing the Microsoft Graph API with graphiti: graphiti.md
  - Decision history: decision-history.md
  - Deployment:
    - Installation: installation.md
    - Docker: docker.md
    - Configuration: configuration.md
    - Single SignOn: single-sign-on.md
    - Requirements: requirements.md
    - Release procedure: release-procedure.md
    - Microsoft Azure: azure/azure-setup-guide.md
  - Operations:
    - Role, Special roles and Alias: roles.md
    - Statistics: statistics.md
    - Grants: grants.md
  - Frontend:
    - Frontend Architecture: architecture/frontend.md
    - Buttons: frontend/buttons/buttons.md
    - Icons: frontend/icons.md
    - Components: frontend/components/utility.md
    - Tables: frontend/tables.md
  - Other:
    - Reusable components: reusable-components.md
    - Release notes: changelog.md
