site_name: OS2Datascanner Docs
site_url: https://os2datascanner.rtfd.io

theme: readthedocs

markdown_extensions:
  - sane_lists

nav:
  - Overview: index.md
  - Data sources: data-sources.md
  - Development environment: dev-environment.md
  - Management Commands: management-commands.md
  - The engine:
    - Engine/pipeline: architecture/pipeline.md
    - Engine/RabbitMQ: architecture/rabbitmq.md
    - The model: engine2.md
    - The rule engine: rules.md
    - Pre-execution of rules (SmartDelta): smartdelta.md
  - Security Architecture: architecture/security.md
  - Scan API: api.md
  - Accessing the Microsoft Graph API with graphiti: graphiti.md
  - Decision history: decision-history.md
  - Deployment:
    - Installation: installation.md
    - Docker: docker.md
    - Configuration: configuration.md
    - Single SignOn: single-sign-on.md
    - Requirements: requirements.md
    - Release procedure: release-procedure.md
    - Microsoft Azure: azure/azure-setup-guide.md
  - Operations:
    - Role, Special roles and Alias: roles.md
  - Frontend:
    - Frontend Architecture: architecture/frontend.md
    - Buttons: frontend/buttons/buttons.md
    - Icons: frontend/icons.md
    - Components: frontend/components/utility.md
    - Tables: frontend/tables.md
  - Other:
    - Reusable components: reusable-components.md
    - Release notes: changelog.md