# SPDX-FileCopyrightText: 2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

# THIS FILE CONTAINS DEFAULT CONFIGURATION SETTINGS. DO NOT CHANGE!!!
# To change the configuration of a specific instance, go the user configuration
# file. For development, the user configuration file is found here:
# /dev-environment/dev-settings.toml

SECRET_KEY = ""
DECRYPTION_HEX = ""

# django-prometheus will try to connect to postgresql during collectstatic
# without this setting: https://github.com/korfuri/django-prometheus/issues/34.
# It only collects a count of un-run migrations, which we don't really care
# about anyways, so we just leave it off.
PROMETHEUS_EXPORT_MIGRATIONS = false

# [mode]
DEBUG = false
KEYCLOAK_ENABLED = false
SAML2_ENABLED = false

# [functionality]
HANDLE_DROPDOWN = false
ALLOW_CONTACT_MAGENTA = false
ARCHIVE_TAB = true
DPO_CSV_EXPORT = false
LEADER_CSV_EXPORT = false
ALLOW_SHOW_ERRORS = false

# [msgraph]
MSGRAPH_ALLOW_WRITE = false
MSGRAPH_APP_ID = ""
MSGRAPH_CLIENT_SECRET = ""
MSGRAPH_TENANT_ID = ""

# [smb]
SMB_ALLOW_WRITE = false

# [site]
# The URL of this site, used in links in emails and in the redirect URL for
# OAuth 2.0 services. (This value should end with a forward slash.)
SITE_URL = "*"
ALLOWED_HOSTS = []
SESSION_COOKIE_NAME = "sessionid"
# Default value - required to be set properly in production.
# https://docs.djangoproject.com/en/4.2/ref/settings/#csrf-trusted-origins
CSRF_TRUSTED_ORIGINS = []

# Client info from keycloak
OIDC_RP_CLIENT_ID = "OSdatascanner Report"
OIDC_RP_CLIENT_SECRET = ""
# user creation
# Say no to automatic user creation by default; we tend to use import jobs.
OIDC_CREATE_USER = false
# endpoints
OIDC_OP_AUTHORIZATION_ENDPOINT = ""
OIDC_OP_TOKEN_ENDPOINT = ""
OIDC_OP_USER_ENDPOINT = ""
# signing algorithm and key
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_OP_JWKS_ENDPOINT = ""
# redirect urls
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = ""
# login and logout urls
LOGOUT_URL = ""
OIDC_OP_LOGOUT_URL_METHOD = "os2datascanner.projects.report.reportapp.views.views.oidc_op_logout_url_method"

# [installation]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.postgres',
    'os2datascanner.projects.report.reportapp.apps.ReportappConfig',
    'mozilla_django_oidc',
    'django_extensions',
    'django_prometheus',
    'recurrence',
    'channels',
    'channels_redis',
    'django_structlog',
    'os2datascanner.core_organizational_structure.apps.CoreOrganizationalStructureConfig',
    'os2datascanner.projects.report.organizations.apps.OrganizationsConfig',
    'os2datascanner.projects.shared',
    'os2datascanner.projects.grants',
]
AUTHENTICATION_BACKENDS = [
    'os2datascanner.projects.report.reportapp.utils.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# placeholder configs for DEVs. Keys must exist here if they should be read from
# user-config toml
OPTIONAL_APPS = []
OPTIONAL_MIDDLEWARE = []
INTERNAL_IPS = []
# XXX: is actually a dict but initialized as list due to how @toml files are parsed
DEBUG_TOOLBAR_CONFIG = []

AUTH_PROFILE_MODULE = 'os2datascanner.projects.report.reportapp.UserProfile'
ASGI_APPLICATION = "os2datascanner.projects.report.asgi.application"
ROOT_URLCONF = 'os2datascanner.projects.report.urls'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
  '/code/src/os2datascanner/projects/static/dist'
]
NOTIFICATION_INSTITUTION = ""

# Which URL schemes can be used in links to matched objects? (The possible
# entries are "http", "https", "file" and "outlook".)
PERMITTED_URL_SCHEMES = ['http', 'https']


MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_structlog.middlewares.RequestMiddleware',
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

SETTINGS_EXPORT = [
    'DEBUG',
    'HANDLE_DROPDOWN',
    'ALLOW_CONTACT_MAGENTA',
    'ARCHIVE_TAB',
    'ALLOW_SHOW_ERRORS',
    'DPO_CSV_EXPORT',
    'LEADER_CSV_EXPORT',
    'MSGRAPH_APP_ID',
    'MSGRAPH_CLIENT_SECRET',
    'MSGRAPH_ALLOW_WRITE',
]

# [internationalization]
LANGUAGE_CODE = "da-dk"
# Paths relative to the project directory should start with "*" while
# absolute paths should start with "/"
_LOCALE_PATHS = [
    ["*", "src", "os2datascanner", "projects", "report", "locale"],
    ["*", "src", "os2datascanner", "core_organizational_structure", "locale"],
    ["*", "src", "os2datascanner", "projects", "grants", "locale"],
]
_LANGUAGES = [
    ["da", "Danish"],
]
TIME_ZONE = "Europe/Copenhagen"
USE_I18N = true
USE_L10N = true
USE_TZ = true
USE_THOUSAND_SEPARATOR = true

# [email]
DEFAULT_FROM_EMAIL = '(Magenta Bibos Info) info@magenta.dk'
ADMIN_EMAIL = '(Magenta Bibos Admin) info@magenta.dk'
EMAIL_HOST = 'localhost'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = false
EMAIL_PORT = 25
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# [logging]
LOG_LEVEL = "INFO"

SHELL_PLUS_IMPORTS = ["from os2datascanner._interactive import *"]

[DATABASES]

    [DATABASES.default]
    ENGINE = "django_prometheus.db.backends.postgresql"
    NAME = "os2datascanner_report"
    USER = "os2datascanner_report"
    PASSWORD = ""
    HOST = "127.0.0.1"

[DATABASE_POOL_ARGS]
max_overflow = 10
pool_size = 5
recycle = 300

# The full documentation can be found here: https://github.com/fangli/django-saml2-auth
[SAML2_AUTH]

# Metadata is required, choose either remote url or local file path
METADATA_AUTO_CONF_URL = ''
METADATA_LOCAL_FILE_PATH = ''

# Optional settings below
DEFAULT_NEXT_URL = '/admin'  # Custom target redirect URL after the user get logged in. Default to /admin if not set. This setting will be overwritten if you have parameter ?next= specificed in the login URL.
CREATE_USER = false # Create a new Django user when a new user logs in. Only set this to True, if you're not going to import organizational structure.
ASSERTION_URL = 'https://mysite.com' # Custom URL to validate incoming SAML requests against
ENTITY_ID = 'https://mysite.com/saml2_auth/acs/' # Populates the Issuer element in authn request
NAME_ID_FORMAT = 'FormatString' # Sets the Format property of authn NameIDPolicy element
ACCEPTED_TIME_DIFF = 0
USE_JWT = false # Set this to True if you are running a Single Page Application (SPA) with Django Rest Framework (DRF), and are using JWT authentication to authorize client users
FRONTEND_URL = 'https://myfrontendclient.com' # Redirect URL for the client if you are using JWT auth with DRF. See explanation below
# Samlt assertion signage
CERT_FILE = ''
KEY_FILE = ''

AUTHN_REQUESTS_SIGNED = false
WANT_ASSERTIONS_SIGNED = false
WANT_RESPONSE_SIGNED = false
TOKEN_REQUIRED = false

    [SAML2_AUTH.NEW_USER_PROFILE]
    USER_GROUPS = []  # The default group name when a new user logs in
    ACTIVE_STATUS = true  # The default active status for new users
    STAFF_STATUS = true  # The staff status for new users
    SUPERUSER_STATUS = false  # The superuser status for new users

    [SAML2_AUTH.ATTRIBUTES_MAP]
    # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
    email = 'email'
    username = 'username'
    first_name = 'first_name'
    last_name = 'last_name'
    sid = 'sid'

    [SAML2_AUTH.TRIGGER]
    CREATE_USER = 'path.to.your.new.user.hook.method'
    BEFORE_LOGIN = 'path.to.your.login.hook.method'

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "queue"
AMQP_USER = "guest"
AMQP_PWD = "guest"
AMQP_SCHEME = "amqp"
AMQP_PORT = 5672
AMQP_HEARTBEAT = 6000
AMQP_VHOST = "/"
    [amqp.AMQP_BACKOFF_PARAMS]
    max_tries = 10
    ceiling = 7
    warn_after = 6
    fuzz = 0

[dirs]
# These are the settings for various directories.
# Paths relative to the project directory should start with "*" while
# absolute paths should start with "/"
BUILD_DIR = ["*", "build"]
VAR_DIR = ["*", "var"]
LOGS_DIR = ["*", "var", "logs"]
STATIC_ROOT = ["*", 'src', 'os2datascanner', 'projects', 'static', 'report']
MEDIA_ROOT = ["*", "src", "os2datascanner", "projects", "report", "media", "images"]
# loglevel for components from engine
[log]
log_path = ""
log_level = "INFO"
