[server]
# An optional list of the Source type labels that the API host may scan. If
# this list is non-empty, other types of Source will be rejected
permitted_sources = ["data", "web"]
# The RFC 6750-style bearer token that must be included (in the "Authorization"
# header) in all requests to the API host. If this value is empty, the API host
# will reject all incoming requests
token = ""

[log]
log_path = ""
log_level = "INFO"
