# Generated by Django 3.2.11 on 2023-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0019_config_verbosename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconfig',
            name='users_dn',
            field=models.TextField(help_text="Distinguished name for the (top) OU in which to search for users. Groups present under this OU will not necessarily be imported, as OSdatascanner reconstructs groups based on users' group memberships.", verbose_name='DN for users (OU)'),
        ),
    ]
