# Generated by Django 3.2.11 on 2024-01-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0020_alter_ldapconfig_users_dn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='object_sid_attribute',
            field=models.CharField(blank=True, help_text="Name of LDAP attribute, which stores the object security identifier. (SID) Often this is stored as 'objectSid' or 'securityIdentifier'. Without this attribute, OSdatascanner will not be able to identify the owner of on-premise files.", max_length=64, null=True, verbose_name='Object security identifier'),
        ),
        migrations.AddField(
            model_name='ldapconfig',
            name='object_sid_mapper_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
