# Generated by Django 3.2.11 on 2024-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0022_remove_sid_uuid_add_first_name_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='custom_user_filter',
            field=models.TextField(blank=True, help_text="Additional LDAP Filter for filtering searched users. Leave this empty if you don't need additional filter. Make sure that it starts with '(' and ends with ')'", null=True, verbose_name='custom LDAP user filter'),
        ),
    ]
