# Generated by Django 3.2.11 on 2024-06-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0023_ldapconfig_custom_user_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='group_filter',
            field=models.CharField(blank=True, default='', help_text='Groups will only be imported, if their name begins with the given string. Only works for group based imports. ', max_length=64, verbose_name='group prefix filter'),
        ),
    ]
