# Generated by Django 3.2.11 on 2025-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0028_remove_ldapconf_old_auth_require_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='upn_attribute',
            field=models.CharField(blank=True, help_text="Name of the LDAP attribute containing the user principal name, the modern Windows unique account identifier that looks like an e-mail address. This is usually just 'userPrincipalName'.", max_length=64, null=True, verbose_name='User principal name LDAP attribute'),
        ),
    ]
