# Generated by Django 5.2.1 on 2025-07-28 12:22

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0029_ldapconfig_upn_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphimportjob',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msgraphconfiguration',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
