# Generated by Django 5.2.1 on 2025-07-28 12:22

from django.db import migrations

def set_grant_uuid(apps, schema_editor):
    MSGraphImportJob = apps.get_model('import_services', 'MSGraphImportJob')
    MSGraphConfiguration = apps.get_model('import_services', 'MSGraphConfiguration')

    for import_job in MSGraphImportJob.objects.iterator():
        import_job.grant_uuid = import_job.grant.uuid
        import_job.save(update_fields=['grant_uuid'])

    for conf in MSGraphConfiguration.objects.iterator():
        conf.grant_uuid = conf.grant.uuid
        conf.save(update_fields=['grant_uuid'])


class Migration(migrations.Migration):

    run_before = ('grants', '0018_remove_ewsgrant_id_remove_googleapigrant_id_and_more'),

    dependencies = [
        ('import_services', '0030_msgraphimportjob_grant_uuid'),
        ('grants', '0017_set_unique'),
    ]

    operations = [
        migrations.RunPython(set_grant_uuid, reverse_code=migrations.RunPython.noop),
    ]
