# Generated by Django 5.2.1 on 2025-07-28 12:33

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0020_grant_inherit_link'),
        ('import_services', '0031_msgraph_importjob_set_grant_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgraphimportjob',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='msgraphconfiguration',
            name='grant',
        ),
        migrations.RenameField(
            model_name='msgraphimportjob',
            old_name='grant_uuid',
            new_name='grant',
        ),
        migrations.RenameField(
            model_name='msgraphconfiguration',
            old_name='grant_uuid',
            new_name='grant',
        ),
    ]
