# Generated by Django 5.2.1 on 2025-07-28 12:34

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0032_remove_and_rename_msgraph_import_and_conf_grant'),
    ]


    operations = [

        migrations.AlterField(
            model_name='msgraphimportjob',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.graphgrant'),
        ),

        migrations.AlterField(
            model_name='msgraphconfiguration',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='grants.graphgrant'),
        ),

    ]