# Generated by Django 5.2.1 on 2025-09-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0033_foreignkey_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='importservice',
            name='hide_units_on_import',
            field=models.BooleanField(default=False, help_text='hide new organizational units by default', verbose_name='hide new units on import'),
        ),
    ]
