# Generated by Django 5.2.1 on 2025-09-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0034_importservice_hide_units_on_import'),
        ('organizations', '0063_grantextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapimportjob',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importjobs', to='import_services.realm'),
        ),
        migrations.AlterField(
            model_name='msgraphimportjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msimportjobs', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='os2moimportjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os2moimportjobs', to='organizations.organization', verbose_name='organization'),
        ),
    ]
