# Generated by Django 5.2.1 on 2025-12-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_backgroundjob__exec_state'),
        ('grants', '0020_grant_inherit_link'),
        ('import_services', '0035_alter_ldapimportjob_realm_and_more'),
        ('organizations', '0068_account_distinguished_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWorkspaceConfig',
            fields=[
                ('importservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='import_services.importservice')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(verbose_name='last modified')),
                ('last_exported', models.DateTimeField(blank=True, null=True, verbose_name='last successful export')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='marked for deletion at')),
                ('delegated_admin_email', models.EmailField(help_text='Admin user to impersonate when accessing Workspace APIs', max_length=254, verbose_name='Delegated admin email')),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.googleapigrant', verbose_name='Google API Grant')),
            ],
            options={
                'verbose_name': 'Google Workspace configuration',
                'verbose_name_plural': 'Google Workspace configurations',
            },
            bases=('import_services.importservice', models.Model),
        ),
        migrations.CreateModel(
            name='GoogleWorkspaceImportJob',
            fields=[
                ('backgroundjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.backgroundjob')),
                ('delegated_admin_email', models.EmailField(max_length=254, verbose_name='Delegated admin email used for this run')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.googleapigrant', verbose_name='Google API Grant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googleworkspaceimportjobs', to='organizations.organization', verbose_name='organization')),
            ],
            bases=('core.backgroundjob',),
        ),
    ]
