# Generated by Django 5.2.1 on 2026-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0036_googleworkspaceconfig_googleworkspaceimportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconfig',
            name='search_scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'One level'), (2, 'Subtree')], help_text='For one level, the search applies only for users in the DNs specified by User DNs. For subtree, the search applies to the whole subtree. See LDAP documentation for more details.', verbose_name='search scope'),
        ),
        migrations.AlterField(
            model_name='ldapconfig',
            name='vendor',
            field=models.CharField(choices=[('ad', 'Active Directory'), ('other', 'Other')], max_length=32, verbose_name='vendor'),
        ),
    ]
