# Generated by Django 5.2.1 on 2026-01-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0037_alter_ldapconfig_search_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconfig',
            name='search_scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kun øverste lag'), (2, 'Hele undertræet')], help_text='For one level, the search applies only for users in the DNs specified by User DNs. For subtree, the search applies to the whole subtree. See LDAP documentation for more details.', verbose_name='search scope'),
        ),
        migrations.AlterField(
            model_name='ldapconfig',
            name='vendor',
            field=models.CharField(choices=[('ad', 'Active Directory'), ('other', 'Anden leverandør')], max_length=32, verbose_name='vendor'),
        ),
    ]
