# Generated by Django 5.2.1 on 2026-02-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0038_alter_ldapconfig_search_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphconfiguration',
            name='exclude_guests',
            field=models.BooleanField(default=False, help_text='Should guest users (#EXT#) be excluded from the import?', verbose_name='exclude guest users'),
        ),
        migrations.AddField(
            model_name='msgraphimportjob',
            name='exclude_guests',
            field=models.BooleanField(default=False, help_text='Should guest users (#EXT#) be excluded from the import?'),
        ),
    ]
