# Generated by Django 5.2.1 on 2026-04-28 10:48

import django.db.models.deletion
from django.db import migrations, models


def copy_realms(apps, schema_editor):
    Realm = apps.get_model("import_services", "Realm")
    TempRealm = apps.get_model("import_services", "TempRealm")

    for realm in Realm.objects.iterator():
        TempRealm.objects.create(
            realm_id=realm.realm_id,
            organization=realm.organization,
            created=realm.created,
            last_modified=realm.last_modified,
            last_exported=realm.last_exported,
            deleted_at=realm.deleted_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0039_msgraph_configuration_and_import_exclude_guests'),
        ('organizations', '0071_welcome_logon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRealm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(verbose_name='last modified')),
                ('last_exported', models.DateTimeField(blank=True, null=True, verbose_name='last successful export')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='marked for deletion at')),
                ('realm_id', models.SlugField(allow_unicode=True, unique=True, verbose_name='realm id')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='temp_realm', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'Keycloak realm',
                'verbose_name_plural': 'Keycloak realms',
            },
        ),
        migrations.RunPython(
            code=copy_realms,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
