# Generated by Django 5.2.1 on 2026-04-28 11:15

import django.db.models.deletion
from django.db import migrations, models


def copy_realm_foreign_keys(apps, schema_editor):
    Realm = apps.get_model("import_services", "Realm")
    TempRealm = apps.get_model("import_services", "TempRealm")
    KeycloakClient = apps.get_model("import_services", "KeycloakClient")
    AuthenticationFlow = apps.get_model("import_services", "AuthenticationFlow")
    FlowExecution = apps.get_model("import_services", "FlowExecution")
    IdentityProvider = apps.get_model("import_services", "IdentityProvider")
    LDAPImportJob = apps.get_model("import_services", "LDAPImportJob")

    for model in (KeycloakClient, AuthenticationFlow, FlowExecution, IdentityProvider, LDAPImportJob):
        for obj in model.objects.iterator():
            obj.temp_realm = TempRealm.objects.get(realm_id=obj.realm.realm_id)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0040_temprealm'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationflow',
            name='temp_realm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_flows', to='import_services.temprealm'),
        ),
        migrations.AddField(
            model_name='flowexecution',
            name='temp_realm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_executions', to='import_services.temprealm'),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='temp_realm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='import_services.temprealm'),
        ),
        migrations.AddField(
            model_name='keycloakclient',
            name='temp_realm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='import_services.temprealm'),
        ),
        migrations.AddField(
            model_name='ldapimportjob',
            name='temp_realm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importjobs', to='import_services.temprealm'),
        ),
        migrations.RunPython(
            code=copy_realm_foreign_keys,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
