# Generated by Django 5.2.1 on 2026-04-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0041_copy_realm_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticationflow',
            name='realm',
        ),
        migrations.RemoveField(
            model_name='flowexecution',
            name='realm',
        ),
        migrations.RemoveField(
            model_name='ldapimportjob',
            name='realm',
        ),
        migrations.RemoveField(
            model_name='identityprovider',
            name='realm',
        ),
        migrations.RemoveField(
            model_name='keycloakclient',
            name='realm',
        ),
        migrations.DeleteModel(
            name='Realm',
        ),
    ]
