# Generated by Django 5.2.1 on 2026-04-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0042_remove_old_realm'),
        ('organizations', '0071_welcome_logon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempRealm',
            new_name='Realm',
        ),
        migrations.RenameField(
            model_name='authenticationflow',
            old_name='temp_realm',
            new_name='realm',
        ),
        migrations.RenameField(
            model_name='flowexecution',
            old_name='temp_realm',
            new_name='realm',
        ),
        migrations.RenameField(
            model_name='identityprovider',
            old_name='temp_realm',
            new_name='realm',
        ),
        migrations.RenameField(
            model_name='keycloakclient',
            old_name='temp_realm',
            new_name='realm',
        ),
        migrations.RenameField(
            model_name='ldapimportjob',
            old_name='temp_realm',
            new_name='realm',
        ),
    ]
