# Generated by Django 5.2.1 on 2026-04-28 11:24

import django.db.models.deletion
from django.db import migrations, models


def remove_dead_objects(apps, schema_editor):
    KeycloakClient = apps.get_model("import_services", "KeycloakClient")
    AuthenticationFlow = apps.get_model("import_services", "AuthenticationFlow")
    FlowExecution = apps.get_model("import_services", "FlowExecution")
    IdentityProvider = apps.get_model("import_services", "IdentityProvider")
    LDAPImportJob = apps.get_model("import_services", "LDAPImportJob")

    for model in (KeycloakClient, AuthenticationFlow, FlowExecution, IdentityProvider, LDAPImportJob):
        model.objects.filter(realm__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0043_rename_temprealm_realm_and_more'),
        ('organizations', '0071_welcome_logon'),
    ]

    operations = [
        migrations.RunPython(
            code=remove_dead_objects,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='authenticationflow',
            name='realm',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_flows', to='import_services.realm'),
        ),
        migrations.AlterField(
            model_name='flowexecution',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_executions', to='import_services.realm'),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='realm',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='import_services.realm'),
        ),
        migrations.AlterField(
            model_name='keycloakclient',
            name='realm',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='import_services.realm'),
        ),
        migrations.AlterField(
            model_name='ldapimportjob',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importjobs', to='import_services.realm'),
        ),
        migrations.AlterField(
            model_name='realm',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='realm', to='organizations.organization', verbose_name='organization'),
        ),
    ]
