# Generated by Django 2.2.10 on 2020-10-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0034_gmailscanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.Rule')),
                ('scanner_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.Scanner')),
            ],
            options={
                'unique_together': {('scanner_job', 'position')},
                'order_with_respect_to': 'scanner_job',
            },
        ),
    ]
