# Generated by Django 2.2.10 on 2020-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0037_remove_scanner_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='scanners', through='os2datascanner.OrderedRule', to='os2datascanner.Rule', verbose_name='Regler'),
        ),
    ]
