# Generated by Django 2.2.18 on 2021-05-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_imported_mixin'),
        ('os2datascanner', '0052_rename_ldap_organization_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangescanner',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.OrganizationalUnit', verbose_name='organizational unit'),
        ),
    ]



