# Generated by Django 2.2.18 on 2021-06-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0057_message_field_to_scanstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanstatus',
            name='message',
            field=models.CharField(
                max_length=2048,
                null=True,
                verbose_name='status message'
            ),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='status_is_error',
            field=models.BooleanField(
                default=False,
                verbose_name='is status failed'
            ),
        ),
    ]
