# Generated by Django 3.2.11 on 2022-03-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0072_scan_status_added_default_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSTeamsScanner',
            fields=[
                ('scanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.scanner')),
                ('tenant_id', models.CharField(max_length=256, verbose_name='Tenant ID')),
            ],
            options={
                'abstract': False,
            },
            bases=('os2datascanner.scanner',),
        ),
    ]
