# Generated by Django 3.2.11 on 2022-05-19 11:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20220504_1940'),
        ('os2datascanner', '0079_usererrorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphTeamsScanner',
            fields=[
                ('scanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.scanner')),
                ('tenant_id', models.CharField(max_length=256, verbose_name='Tenant ID')),
                ('org_unit', mptt.fields.TreeManyToManyField(blank=True, related_name='msgraphteamsscanners', to='organizations.OrganizationalUnit', verbose_name='organizational unit')),
            ],
            options={
                'abstract': False,
            },
            bases=('os2datascanner.scanner',),
        ),
    ]
