# Generated by Django 3.2.11 on 2022-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0081_remove_scheduledcheckup_sc_pc_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererrorlog',
            name='archive_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Arkiveret'), (1, 'Intet foretaget')], db_index=True, null=True, verbose_name='archive status'),
        ),
    ]
