# Generated by Django 3.2.11 on 2023-10-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('os2datascanner', '0086_bye_tenant_id'), ('os2datascanner', '0087_usererrorlog_is_removed'), ('os2datascanner', '0088_usererrorlog_is_new'), ('os2datascanner', '0089_scanstatus_resolved'), ('os2datascanner', '0090_alter_usererrorlog_attributes'), ('os2datascanner', '0091_alter_usererrorlog_options'), ('os2datascanner', '0092_alter_customrule__rule'), ('os2datascanner', '0093_add_field_matches_found'), ('os2datascanner', '0094_remove_scanner_e2_last_run_at'), ('os2datascanner', '0095_analysisjob_typestats'), ('os2datascanner', '0096_usererrorlog_engine_error')]

    dependencies = [
        ('core', '0005_alter_backgroundjob__exec_state_translation'),
        ('os2datascanner', '0085_go_over_to_grants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgraphcalendarscanner',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='msgraphfilescanner',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='msgraphmailscanner',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='scanstatus',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='resolved'),
        ),
        migrations.AddField(
            model_name='usererrorlog',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is new'),
        ),
        migrations.AddField(
            model_name='usererrorlog',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is removed'),
        ),
        migrations.AlterModelOptions(
            name='usererrorlog',
            options={'verbose_name': 'error log', 'verbose_name_plural': 'error logs'},
        ),
        migrations.AlterField(
            model_name='customrule',
            name='_rule',
            field=models.JSONField(verbose_name='Rule'),
        ),
        migrations.AddField(
            model_name='scanstatus',
            name='matches_found',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='matches found'),
        ),
        migrations.AddField(
            model_name='scanstatussnapshot',
            name='matches_found',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='matches found'),
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='e2_last_run_at',
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('backgroundjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.backgroundjob')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.scanner')),
            ],
            bases=('core.backgroundjob',),
        ),
        migrations.CreateModel(
            name='TypeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.TextField(verbose_name='Mime type')),
                ('sizes', models.JSONField(blank=True, null=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='os2datascanner.analysisjob')),
            ],
        ),
        migrations.AddField(
            model_name='usererrorlog',
            name='engine_error',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
