# Generated by Django 3.2.11 on 2023-08-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0108_update_healthrule_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='exclusion_rules',
        ),
    ]
