# Generated by Django 3.2.11 on 2023-10-09 08:54

from django.db import migrations

from os2datascanner.engine2.rules.cpr import CPRRule
from os2datascanner.projects.admin.adminapp.models.sensitivity_level import (
    Sensitivity,
)


def create_default_cprrule_and_organization(apps, schema_editor):
    CPRRuleModel = apps.get_model("os2datascanner", "CPRRule")
    CustomRule = apps.get_model("os2datascanner", "CustomRule")
    Scanner = apps.get_model("os2datascanner", "Scanner")

    # Get the old CPR rule and select the scanner jobs that use it.
    old_cpr = CPRRuleModel.objects.filter(name="CPR regel").first()
    if old_cpr is not None:
        jobs = list(Scanner.objects.filter(rules=old_cpr))
        old_cpr.delete()
    else:
        jobs = []

    if CustomRule.objects.filter(name="CPR regel").first() is None:
        new_cpr = CustomRule.objects.get_or_create(
            name="CPR regel",
            description="Denne regel finder alle gyldige CPR numre.",
            sensitivity=Sensitivity.CRITICAL,
            _rule=CPRRule(
                modulus_11=True,
                ignore_irrelevant=True,
                examine_context=True).to_json_object())

        # If there are any jobs that used the old cpr rule
        # add the new one instead.
        for job in jobs:
            job.rules.add(new_cpr)

    print("SUCCESS! Default rule: 'CPR Regel' exists in the database.")


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0112_turbohealthrule'),
    ]

    operations = [
        migrations.RunPython(
            create_default_cprrule_and_organization,
            reverse_code=migrations.RunPython.noop)
    ]
