# Generated by Django 3.2.11 on 2023-11-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0113_scanner_keep_false_positives'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailscanner',
            name='skip_attachments',
            field=models.BooleanField(default=False, help_text='Do not scan files attachmented to an email. Be careful using this setting as a lot of attachments might contain sought-after matches.', verbose_name='skip attachments'),
        ),
    ]
