# Generated by Django 3.2.11 on 2023-12-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0115_coveredaccount_scan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveredaccount',
            name='scan_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.scanstatus'),
        ),
    ]
