# Generated by Django 3.2.11 on 2024-01-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0115_remove_rule_models_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='exclusion_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scanners_ex_rule', to='os2datascanner.rule', verbose_name='exclusion rule'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scanners', to='os2datascanner.rule', verbose_name='rule'),
            preserve_default=False,
        )
    ]
