# Generated by Django 3.2.11 on 2023-12-14 15:17

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q, F

from os2datascanner.engine2.pipeline import messages


def pre_populate_coveredaccount_scan_status(apps, schema_editor) -> None:
    CoveredAccount = apps.get_model("os2datascanner", "CoveredAccount")
    _completed_Q = (
            Q(total_objects__gt=0)
            & Q(explored_sources=F('total_sources'))
            & Q(scanned_objects__gte=F('total_objects')))

    for cva in CoveredAccount.objects.iterator():
        scanner = cva.scanner
        finished_statuses = scanner.statuses.filter(_completed_Q)
        last = max(finished_statuses, key=lambda
            status: messages.ScanTagFragment.from_json_object(status.scan_tag).time, default=None)
        cva.scan_status = last

        cva.save()


class Migration(migrations.Migration):
    dependencies = [
        ('os2datascanner', '0119_manage_coveredaccount_ourselves'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveredaccount',
            name='scan_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='os2datascanner.scanstatus'),
        ),
        migrations.RunPython(pre_populate_coveredaccount_scan_status,
                             reverse_code=migrations.RunPython.noop)
    ]
