# Generated by Django 3.2.11 on 2023-12-19 12:47

from django.db import migrations, models
import django.db.models.deletion


def drop_broken_covered_accounts(apps, schema_editor) -> None:
    CoveredAccount = apps.get_model("os2datascanner", "CoveredAccount")
    CoveredAccount.objects.filter(scan_status__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0120_coveredaccount_scan_status'),
    ]

    operations = [
        migrations.RunPython(drop_broken_covered_accounts,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='coveredaccount',
            name='scan_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.scanstatus'),
        ),
    ]
