# Generated by Django 3.2.11 on 2024-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0122_clear_unrelated_coveredaccounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coveredaccount',
            options={'get_latest_by': 'scan_status__scan_tag__time'},
        ),
        migrations.RemoveConstraint(
            model_name='coveredaccount',
            name='os2datascanner_scanner_c_scanner_id_account_id_ec9ff164_uniq',
        ),
        migrations.AddConstraint(
            model_name='coveredaccount',
            constraint=models.UniqueConstraint(fields=('scanner', 'account', 'scan_status'), name='os2datascanner_coveredaccount_no_exact_dupes'),
        ),
        migrations.AlterModelOptions(
            name='scanstatus',
            options={'get_latest_by': 'scan_tag__time', 'verbose_name': 'scan status', 'verbose_name_plural': 'scan statuses'},
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='covered_accounts',
        ),
    ]
