# Generated by Django 3.2.11 on 2024-02-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0123_coveredaccount_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscanner',
            name='always_crawl',
            field=models.BooleanField(default=False, help_text='instead of just treating the sitemap as a complete list of links, run the crawler on those links as well', verbose_name="crawl the sitemap's content"),
        ),
    ]
