# Generated by Django 3.2.11 on 2024-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0124_webscanner_always_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphmailscanner',
            name='scan_attachments',
            field=models.BooleanField(default=True, help_text='Scan attached files', verbose_name='Scan attachments'),
        ),
    ]
