# Generated by Django 3.2.11 on 2024-03-15 12:44

from django.db import migrations, models

from os2datascanner.engine2.model.core import Handle


def populate_scheduledcheckup_paths(apps, schema_editor):
    ScheduledCheckup = apps.get_model('os2datascanner', 'ScheduledCheckup')

    path_scanner_set = set()

    # Iterate through objects newest to oldest
    for checkup in ScheduledCheckup.objects.order_by("-pk").iterator():
        # Reimplementation of the "handle"-property of the ScheduledCheckup
        # model, since properties cannot be accessed in migrations.
        handle = Handle.from_json_object(checkup.handle_representation)
        path = handle.crunch(hash=True)
        scanner = checkup.scanner
        if (path, scanner) in path_scanner_set:
            # A checkup object with this path already exists -- delete this one!
            checkup.delete()
        else:
            # This is the first instance of this checkup object. Update the path
            # then remember the path and scanner for later.
            path_scanner_set.add((path, scanner))
            checkup.path = path
            checkup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0125_msgraphmailscanner_scan_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcheckup',
            name='path',
            field=models.CharField(default='default', max_length=256, verbose_name='path'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_scheduledcheckup_paths, reverse_code=migrations.RunPython.noop)
    ]
