# Generated by Django 3.2.11 on 2024-04-23 09:20

from django.db import migrations

from os2datascanner.utils.batch import BatchUpdate
from os2datascanner.engine2.model.core import Handle


def recrunch_and_recensor(apps, schema_editor):
    ScheduledCheckup = apps.get_model('os2datascanner', 'ScheduledCheckup')

    with BatchUpdate(
            ScheduledCheckup.objects,
            ["path", "handle_representation"]) as batch:
        for checkup in ScheduledCheckup.objects.order_by("-pk").iterator():
            handle = Handle.from_json_object(checkup.handle_representation)
            handle = handle.censor()

            checkup.path = handle.crunch(hash=True)
            checkup.handle_representation = handle.to_json_object()

            batch.append(checkup)

    print(f"Updated {batch.count} ScheduledCheckups")


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0126_scheduledcheckup_path'),
    ]

    operations = [
        migrations.RunPython(
                recrunch_and_recensor,
                reverse_code=migrations.RunPython.noop)
    ]
