# Generated by Django 3.2.11 on 2024-04-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0126_scheduledcheckup_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='skipped_by_last_modified',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='files skipped by last modified check'),
        ),
        migrations.AddField(
            model_name='scanstatussnapshot',
            name='skipped_by_last_modified',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='files skipped by last modified check'),
        ),
    ]
