# Generated by Django 3.2.11 on 2024-05-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0127_recrunch_and_recensor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scheduledcheckup',
            name='sc_cc_lookup',
        ),
        migrations.AddIndex(
            model_name='scheduledcheckup',
            index=models.Index(fields=['path'], name='scheduled_checkup_path_index'),
        ),
    ]
