# Generated by Django 3.2.11 on 2024-01-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
        ('os2datascanner', '0128_scheduled_checkup_path_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangescanner',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant'),
        ),
    ]
