# Generated by Django 4.0.10 on 2024-06-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0131_scanstatus_skipped_by_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='authentication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_authentication', to='os2datascanner.authentication', verbose_name='username'),
        ),
    ]
