# Generated by Django 3.2.11 on 2024-04-23 06:55

from django.db import migrations, models

def populate_rule_categories(apps, schema_editor):
    RuleCategory = apps.get_model("os2datascanner", "RuleCategory")
    RuleCategory.objects.bulk_create([
        RuleCategory(name="number_id"),
        RuleCategory(name="names"),
        RuleCategory(name="addresses"),
        RuleCategory(name="sick_leave"),
        RuleCategory(name="danish")
    ])

def assign_category_to_cpr_customrule(apps, schema_editor):
    RuleCategory = apps.get_model("os2datascanner", "RuleCategory")
    CustomRule = apps.get_model("os2datascanner", "CustomRule")

    cpr_rule = CustomRule.objects.filter(name="CPR regel")
    if cpr_rule:
        categories = RuleCategory.objects.filter(name__in=("number_id", "danish"))
        rule = cpr_rule.first()
        rule.categories.add(*categories)


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0132_alter_scanner_authentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('number_id', 'number ID'), ('names', 'names'), ('addresses', 'addresses'), ('sick_leave', 'sick leave'), ('danish', 'Danish')], max_length=256, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='customrule',
            name='categories',
            field=models.ManyToManyField(related_name='rules', to='os2datascanner.RuleCategory', verbose_name='categories'),
        ),
        migrations.RunPython(populate_rule_categories, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(assign_category_to_cpr_customrule, reverse_code=migrations.RunPython.noop)
    ]
