# Generated by Django 3.2.11 on 2024-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0134_scanner_dtstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='has an email notification been sent'),
        ),
    ]
