# Generated by Django 3.2.11 on 2024-11-08 07:33

from django.db import migrations, models

def is_removed_to_is_resolved_fields(apps, schema_editor):
    UserErrorLog = apps.get_model('os2datascanner', 'UserErrorLog')
    UserErrorLog.objects.filter(is_removed=True).update(is_resolved=True)

def is_resolved_to_is_removed_fields(apps, schema_editor):
    UserErrorLog = apps.get_model('os2datascanner', 'UserErrorLog')
    UserErrorLog.objects.filter(is_resolved=True).update(is_removed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0135_scanstatus_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usererrorlog',
            options={'permissions': [('can_resolve_usererrorlog', 'Can resolve error log')], 'verbose_name': 'error log', 'verbose_name_plural': 'error logs'},
        ),
        migrations.AddField(
            model_name='usererrorlog',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Is resolved'),
        ),
        migrations.RunPython(is_removed_to_is_resolved_fields, reverse_code=is_resolved_to_is_removed_fields),
        migrations.RemoveField(
            model_name='usererrorlog',
            name='is_removed',
        ),
    ]
