# Generated by Django 3.2.11 on 2024-11-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0135_scanstatus_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usererrorlog',
            options={'permissions': [('can_remove_usererrorlog', 'Can remove error log')], 'verbose_name': 'error log', 'verbose_name_plural': 'error logs'},
        ),
    ]
