# Generated by Django 3.2.11 on 2024-12-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0136_alter_scanner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanner',
            options={'ordering': ['name'], 'permissions': [('can_validate', 'Can validate scannerjobs'), ('hide_scanner', 'Can hide scannerjob from scannerjob list')]},
        ),
        migrations.AddField(
            model_name='scanner',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, verbose_name='hidden'),
        ),
    ]
