# Generated by Django 3.2.11 on 2024-12-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0136_alter_scanner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanstatus',
            options={'get_latest_by': 'scan_tag__time', 'permissions': [('can_export_completed_scans', 'Can export history of completed scans')], 'verbose_name': 'scan status', 'verbose_name_plural': 'scan statuses'},
        ),
    ]
