# Generated by Django 3.2.11 on 2024-12-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0136_alter_scanner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanstatus',
            options={'get_latest_by': 'scan_tag__time', 'permissions': [('resolve_scanstatus', 'Can resolve scan statuses'), ('csv_export_scanstatus', 'Can export data from ScanStatus to a CSV file')], 'verbose_name': 'scan status', 'verbose_name_plural': 'scan statuses'},
        ),
    ]
