# Generated by Django 3.2.11 on 2024-11-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0136_alter_scanner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanstatus',
            name='scan_tag',
            field=models.JSONField(verbose_name='scan tag'),
        ),
    ]
