# Generated by Django 3.2.11 on 2024-12-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0137_hide_scannerjobs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanstatus',
            options={'get_latest_by': 'scan_tag__time', 'permissions': [('export_completed_scanstatus', 'Can export history of completed scans')], 'verbose_name': 'scan status', 'verbose_name_plural': 'scan statuses'},
        ),
    ]
