# Generated by Django 3.2.11 on 2025-01-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0140_scanstatus_resolve_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usererrorlog',
            options={'permissions': [('resolve_usererrorlog', 'Can resolve error log'), ('export_usererrorlog', 'Can export error log to CSV'), ('mark_view_usererrorlog', 'Can mark error log as viewed')], 'verbose_name': 'error log', 'verbose_name_plural': 'error logs'},
        ),
    ]
