# Generated by Django 3.2.11 on 2025-01-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0142_unhide_scanner_and_view_hidden_scanner_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropboxscanner',
            options={'verbose_name': 'Dropboxscanner'},
        ),
        migrations.AlterModelOptions(
            name='exchangescanner',
            options={'verbose_name': 'Exchangescanner'},
        ),
        migrations.AlterModelOptions(
            name='filescanner',
            options={'verbose_name': 'Filescanner'},
        ),
        migrations.AlterModelOptions(
            name='gmailscanner',
            options={'verbose_name': 'Gmail scanner'},
        ),
        migrations.AlterModelOptions(
            name='googledrivescanner',
            options={'verbose_name': 'Google Drive scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphcalendarscanner',
            options={'ordering': ['name'], 'verbose_name': 'MSGraph calendarscanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphfilescanner',
            options={'ordering': ['name'], 'verbose_name': 'MSGraph filescanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphmailscanner',
            options={'ordering': ['name'], 'verbose_name': 'MSGraph mailscanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphteamsfilescanner',
            options={'ordering': ['name'], 'verbose_name': 'MSGraph Teams filescanner'},
        ),
        migrations.AlterModelOptions(
            name='sbsysscanner',
            options={'verbose_name': 'SBSYS scanner'},
        ),
        migrations.AlterModelOptions(
            name='webscanner',
            options={'verbose_name': 'Webscanner'},
        ),
    ]
