# Generated by Django 3.2.11 on 2025-02-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0144_create_admins_and_superadmin_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MIMETypeProcessStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=256, verbose_name='MIME type')),
                ('total_time', models.DurationField(default=0)),
                ('total_size', models.PositiveBigIntegerField(default=0, verbose_name='Total size in bytes')),
                ('object_count', models.PositiveIntegerField(default=0)),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_stats', to='os2datascanner.scanstatus')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mimetypeprocessstat',
            constraint=models.UniqueConstraint(fields=('scan_status', 'mime_type'), name='unique_MIME_type_scan_status'),
        ),
    ]
