# Generated by Django 3.2.11 on 2025-01-29 15:34

from django.db import migrations, models
import django.db.models.deletion

def authentication_to_grant(apps, schema_editor):
    FileScanner = apps.get_model('os2datascanner', 'FileScanner')
    ExchangeScanner = apps.get_model('os2datascanner', 'ExchangeScanner')
    SMBGrant = apps.get_model('grants', 'SMBGrant')
    EWSrant = apps.get_model('grants', 'EWSGrant')

    for file_scanner in FileScanner.objects.iterator():
        if auth := file_scanner.authentication:

            smb_grant, _ = SMBGrant.objects.get_or_create(username=auth.username,
                                           organization=file_scanner.organization,
                                           defaults={
                                               "_password": [auth.iv.hex(), auth.ciphertext.hex()],
                                               "domain": auth.domain,

                                           })
            file_scanner.smb_grant = smb_grant
            file_scanner.save()



    for ews_scanner in ExchangeScanner.objects.iterator():
        if auth := ews_scanner.authentication and ews_scanner.graph_grant:

            ews_grant, _ = EWSrant.objects.get_or_create(username=auth.username,
                                           organization=ews_scanner.organization,
                                           defaults={
                                               "_password": [auth.iv.hex(), auth.ciphertext.hex()],
                                           })
            ews_scanner.ews_grant = ews_grant
            ews_scanner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0147_add_permission_to_admins_superadmin_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangescanner',
            old_name='grant',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='msgraphcalendarscanner',
            old_name='grant',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='msgraphfilescanner',
            old_name='grant',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='msgraphmailscanner',
            old_name='grant',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='msgraphteamsfilescanner',
            old_name='grant',
            new_name='graph_grant',
        ),
        migrations.AddField(
            model_name='exchangescanner',
            name='ews_grant',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='grants.ewsgrant'),
        ),
        migrations.AddField(
            model_name='filescanner',
            name='smb_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='grants.smbgrant'),
        ),
    migrations.RunPython(
                authentication_to_grant,
                reverse_code=migrations.RunPython.noop)
    ]
