# Generated by Django 3.2.11 on 2025-03-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0011_verbose_names'),
        ('os2datascanner', '0149_remove_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangescanner',
            name='ews_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.ewsgrant', verbose_name='EWS grant'),
        ),
        migrations.AlterField(
            model_name='exchangescanner',
            name='graph_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='filescanner',
            name='smb_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.smbgrant', verbose_name='SMB grant'),
        ),
        migrations.AlterField(
            model_name='msgraphcalendarscanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='msgraphfilescanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='msgraphmailscanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='msgraphteamsfilescanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
    ]
