# Generated by Django 3.2.11 on 2025-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0150_grants_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphmailscanner',
            name='scan_subject',
            field=models.BooleanField(default=True, help_text='Scan mail subjects', verbose_name='Scan subjects'),
        ),
    ]
