# Generated by Django 3.2.11 on 2025-03-13 09:15

from django.db import migrations, models
import django.db.models.deletion
import os2datascanner.projects.admin.adminapp.models.scannerjobs.gmail
import os2datascanner.projects.admin.adminapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0012_auto_20250313_1015'),
        ('os2datascanner', '0150_grants_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailscanner',
            name='service_account_file_gmail',
        ),
        migrations.AddField(
            model_name='gmailscanner',
            name='google_api_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.googleapigrant'),
        ),
        migrations.AddField(
            model_name='gmailscanner',
            name='scan_attachments',
            field=models.BooleanField(default=True, help_text='Scan attached files', verbose_name='Scan attachments'),
        ),
        migrations.AlterField(
            model_name='gmailscanner',
            name='user_emails_gmail',
            field=models.FileField(blank=True, null=True, upload_to=os2datascanner.projects.admin.adminapp.utils.upload_path_gmail_users, validators=[os2datascanner.projects.admin.adminapp.models.scannerjobs.gmail.GmailScanner.validate_filetype_csv]),
        ),
    ]
