# Generated by Django 3.2.11 on 2025-02-27 12:17

from django.db import migrations, models
from django.contrib.auth.management import create_permissions


def migrate_permissions(apps, schema_editor):
    """Create Permission-objects now instead of post-migration."""
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def switch_out_delete_for_cancel_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    admins = Group.objects.get(name="admins")
    admins.permissions.remove(Permission.objects.get(codename="delete_scanstatus"))
    admins.permissions.add(Permission.objects.get(codename="cancel_scanstatus"))


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0150_grants_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='cancelled'),
        ),
        migrations.AddField(
            model_name='scanstatussnapshot',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='cancelled'),
        ),
        migrations.AlterModelOptions(
            name='scanstatus',
            options={'get_latest_by': 'scan_tag__time', 'permissions': [('resolve_scanstatus', 'Can resolve scan statuses'), ('export_completed_scanstatus', 'Can export history of completed scans'), ('cancel_scanstatus', 'Can cancel running scan')], 'verbose_name': 'scan status', 'verbose_name_plural': 'scan statuses'},
        ),
        migrations.RunPython(migrate_permissions, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(switch_out_delete_for_cancel_permission, reverse_code=migrations.RunPython.noop),
    ]
