# Generated by Django 3.2.11 on 2025-03-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0151_add_cancelled_field_to_scanstats_and_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangescanner',
            name='scan_subject',
            field=models.BooleanField(default=True, help_text='Scan mail subjects', verbose_name='Scan subjects'),
        ),
        migrations.AddField(
            model_name='gmailscanner',
            name='scan_subject',
            field=models.BooleanField(default=True, help_text='Scan mail subjects', verbose_name='Scan subjects'),
        ),
        migrations.AddField(
            model_name='msgraphmailscanner',
            name='scan_subject',
            field=models.BooleanField(default=True, help_text='Scan mail subjects', verbose_name='Scan subjects'),
        ),
    ]
