# Generated by Django 3.2.11 on 2025-03-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0013_add_last_updated'),
        ('os2datascanner', '0151_add_cancelled_field_to_scanstats_and_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailscanner',
            name='service_account_file_gmail',
        ),
        migrations.RemoveField(
            model_name='gmailscanner',
            name='user_emails_gmail',
        ),
        migrations.AddField(
            model_name='gmailscanner',
            name='google_api_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.googleapigrant'),
        ),
        migrations.RemoveField(
            model_name='googledrivescanner',
            name='service_account_file',
        ),
        migrations.AddField(
            model_name='googledrivescanner',
            name='google_api_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.googleapigrant'),
        ),
    ]
