# Generated by Django 3.2.11 on 2025-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0151_msgraphmailscanner_scan_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangescanner',
            name='scan_subject',
            field=models.BooleanField(default=True, help_text='Scan mail subjects', verbose_name='Scan subjects'),
        ),
    ]
