# Generated by Django 3.2.11 on 2025-03-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0152_gmail_remove_file_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledrivescanner',
            name='user_emails',
        ),
    ]
