# Generated by Django 3.2.11 on 2025-04-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0152_gmail_remove_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangescanner',
            name='scan_subject',
            field=models.BooleanField(default=True, help_text='Scan mail subjects', verbose_name='Scan subjects'),
        ),
        migrations.AddField(
            model_name='gmailscanner',
            name='scan_subject',
            field=models.BooleanField(default=True, help_text='Scan mail subjects', verbose_name='Scan subjects'),
        ),
        migrations.AddField(
            model_name='msgraphmailscanner',
            name='scan_subject',
            field=models.BooleanField(default=True, help_text='Scan mail subjects', verbose_name='Scan subjects'),
        ),
    ]
