# Generated by Django 3.2.11 on 2025-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0152_gmail_remove_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailscanner',
            name='scan_attachments',
            field=models.BooleanField(default=True, verbose_name='Scan attachments', help_text='Scan attached files'),
        ),
    ]
