# Generated by Django 3.2.11 on 2025-04-08 06:39

from django.db import migrations, models


def set_scan_entire_org(apps, schema_editor):
    Scanner = apps.get_model('os2datascanner', 'Scanner')

    for scanner in Scanner.objects.iterator():
        scanner.scan_entire_org = not scanner.org_unit.exists()
        scanner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0155_gmail_add_scan_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='scan_entire_org',
            field=models.BooleanField(default=False, verbose_name='scan all accounts in organization'),
        ),
        migrations.RunPython(
            set_scan_entire_org,
            reverse_code=migrations.RunPython.noop
        ),
    ]
