# Generated by Django 3.2.11 on 2025-05-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0158_msgraphsharepointscanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropboxscanner',
            options={'verbose_name': 'Dropbox scanner'},
        ),
        migrations.AlterModelOptions(
            name='exchangescanner',
            options={'verbose_name': 'Exchange scanner'},
        ),
        migrations.AlterModelOptions(
            name='filescanner',
            options={'verbose_name': 'File scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphcalendarscanner',
            options={'ordering': ['name'], 'verbose_name': 'MSGraph calendar scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphfilescanner',
            options={'ordering': ['name'], 'verbose_name': 'MSGraph file scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphmailscanner',
            options={'ordering': ['name'], 'verbose_name': 'MSGraph mail scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphteamsfilescanner',
            options={'ordering': ['name'], 'verbose_name': 'MSGraph Teams file scanner'},
        ),
        migrations.AlterModelOptions(
            name='webscanner',
            options={'verbose_name': 'Web scanner'},
        ),
    ]
