# Generated by Django 4.2.21 on 2025-06-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0159_change_verbose_names_for_scanners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msgraphcalendarscanner',
            options={'ordering': ['name'], 'verbose_name': 'Microsoft 365 calendar scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphfilescanner',
            options={'ordering': ['name'], 'verbose_name': 'Microsoft 365 file scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphmailscanner',
            options={'ordering': ['name'], 'verbose_name': 'Microsoft 365 mail scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphsharepointscanner',
            options={'ordering': ['name'], 'verbose_name': 'Microsoft 365 SharePoint scanner'},
        ),
        migrations.AlterModelOptions(
            name='msgraphteamsfilescanner',
            options={'ordering': ['name'], 'verbose_name': 'Microsoft 365 Teams file scanner'},
        ),
    ]
