# Generated by Django 4.2.21 on 2025-06-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0058_alter_alias_shared'),
        ('os2datascanner', '0159_change_verbose_names_for_scanners'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphSharePointSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='site id')),
                ('name', models.TextField(default='Unnamed Site', verbose_name='site name')),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharepoint_site', to='organizations.organization', verbose_name='organization')),
            ],
        ),
        migrations.AddField(
            model_name='msgraphsharepointscanner',
            name='sharepoint_sites',
            field=models.ManyToManyField(blank=True, related_name='sites', to='os2datascanner.msgraphsharepointsite', verbose_name='SharePoint sites to scan'),
        ),
    ]
