# Generated by Django 4.2.21 on 2025-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0160_alter_msgraphcalendarscanner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphSharePointSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(unique=True, verbose_name='site id')),
                ('name', models.TextField(default='Unnamed Site', verbose_name='site name')),
            ],
        ),
        migrations.AddField(
            model_name='msgraphsharepointscanner',
            name='sharepoint_sites',
            field=models.ManyToManyField(blank=True, related_name='scanners', to='os2datascanner.msgraphsharepointsite', verbose_name='SharePoint sites to scan'),
        ),
    ]
