# Generated by Django 5.2.1 on 2025-07-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0014_alter_ewsgrant_organization_and_more'),
        ('os2datascanner', '0160_alter_msgraphcalendarscanner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBSYSDBScanner',
            fields=[
                ('scanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.scanner')),
                ('db_server', models.CharField(help_text='The network name of the SQL Server instance used by your SBSYS installation.', verbose_name='SBSYS database server')),
                ('db_port', models.IntegerField(default=1433, help_text='The port on which to connect to the SQL Server instance.', verbose_name='SBSYS database service port')),
                ('db_name', models.CharField(default='SbSysNetDrift', help_text='The name of the SBSYS database.', verbose_name='SBSYS database name')),
                ('weblink', models.CharField(blank=True, help_text='The base URL of the SBSYS A-sag instance for your SBSYS installation, used to build web links to SBSYS cases.', verbose_name='SBSYS A-sag link')),
                ('grant', models.ForeignKey(help_text='A service account with access to the SQL Server instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.smbgrant', verbose_name='Service account')),
            ],
            options={
                'verbose_name': 'SBSYS database scanner',
                'verbose_name_plural': 'SBSYS database scanners',
            },
            bases=('os2datascanner.scanner',),
        ),
    ]
