# Generated by Django 5.2.1 on 2025-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0162_msgraphsharepointsite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangescanner',
            name='ews_grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangescanner',
            name='graph_grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filescanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailscanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googledrivescanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msgraphcalendarscanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msgraphfilescanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msgraphmailscanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msgraphsharepointscanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msgraphteamsfilescanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sbsysdbscanner',
            name='grant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
