# Generated by Django 5.2.1 on 2025-08-01 09:14

from django.db import migrations


def set_grant_uuid(apps, schema_editor):
    GoogleDriveScanner = apps.get_model('os2datascanner', 'GoogleDriveScanner')
    GmailScanner = apps.get_model('os2datascanner', 'GmailScanner')
    FileScanner = apps.get_model('os2datascanner', 'FileScanner')
    ExchangeScanner = apps.get_model('os2datascanner', 'ExchangeScanner')
    MSGraphMailScanner = apps.get_model('os2datascanner', 'MSGraphMailScanner')
    MSGraphFileScanner = apps.get_model('os2datascanner', 'MSGraphFileScanner')
    MSGraphCalendarScanner = apps.get_model('os2datascanner', 'MSGraphCalendarScanner')
    MSGraphTeamsFileScanner = apps.get_model('os2datascanner', 'MSGraphTeamsFileScanner')
    MSGraphSharepointScanner = apps.get_model('os2datascanner', 'MSGraphSharepointScanner')
    SBSYSDBScanner = apps.get_model('os2datascanner', 'SBSYSDBScanner')

    for google_model in [GoogleDriveScanner, GmailScanner]:
        for scanner in google_model.objects.iterator():
            scanner.grant_uuid =  scanner.google_api_grant.uuid
            scanner.save(update_fields=['grant_uuid'])

    for scanner in FileScanner.objects.iterator():
        scanner.grant_uuid =  scanner.smb_grant.uuid
        scanner.save(update_fields=['grant_uuid'])

    for scanner in ExchangeScanner.objects.iterator():
        scanner.graph_grant_uuid = scanner.graph_grant.uuid if scanner.graph_grant else None
        scanner.ews_grant_uuid = scanner.ews_grant.uuid if scanner.ews_grant else None
        scanner.save(update_fields=['graph_grant_uuid', 'ews_grant_uuid'])

    for msgraph_model in [MSGraphMailScanner, MSGraphFileScanner, MSGraphCalendarScanner,
                          MSGraphTeamsFileScanner, MSGraphSharepointScanner]:
        for scanner in msgraph_model.objects.iterator():
            scanner.grant_uuid = scanner.graph_grant.uuid
            scanner.save(update_fields=['grant_uuid'])

    for scanner in SBSYSDBScanner.objects.iterator():
        scanner.grant_uuid = scanner.grant.uuid
        scanner.save(update_fields=['grant_uuid'])

class Migration(migrations.Migration):

    run_before = ('grants', '0018_remove_ewsgrant_id_remove_googleapigrant_id_and_more'),

    dependencies = [
        ('os2datascanner', '0163_exchangescanner_ews_grant_uuid_and_more'),
        ('grants', '0017_set_unique'),
    ]

    operations = [
        migrations.RunPython(set_grant_uuid, reverse_code=migrations.RunPython.noop),
    ]

