# Generated by Django 5.2.1 on 2025-08-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0164_populate_scanner_grant_uuids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangescanner',
            name='ews_grant',
        ),
        migrations.RemoveField(
            model_name='exchangescanner',
            name='graph_grant',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='smb_grant',
        ),
        migrations.RemoveField(
            model_name='gmailscanner',
            name='google_api_grant',
        ),
        migrations.RemoveField(
            model_name='googledrivescanner',
            name='google_api_grant',
        ),
        migrations.RemoveField(
            model_name='msgraphcalendarscanner',
            name='graph_grant',
        ),
        migrations.RemoveField(
            model_name='msgraphfilescanner',
            name='graph_grant',
        ),
        migrations.RemoveField(
            model_name='msgraphmailscanner',
            name='graph_grant',
        ),
        migrations.RemoveField(
            model_name='msgraphsharepointscanner',
            name='graph_grant',
        ),
        migrations.RemoveField(
            model_name='msgraphteamsfilescanner',
            name='graph_grant',
        ),
        migrations.RemoveField(
            model_name='sbsysdbscanner',
            name='grant',
        ),
    ]
