# Generated by Django 5.2.1 on 2025-08-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0165_remove_exchangescanner_ews_grant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangescanner',
            old_name='ews_grant_uuid',
            new_name='ews_grant',
        ),
        migrations.RenameField(
            model_name='exchangescanner',
            old_name='graph_grant_uuid',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='filescanner',
            old_name='grant_uuid',
            new_name='smb_grant',
        ),
        migrations.RenameField(
            model_name='gmailscanner',
            old_name='grant_uuid',
            new_name='google_api_grant',
        ),
        migrations.RenameField(
            model_name='googledrivescanner',
            old_name='grant_uuid',
            new_name='google_api_grant',
        ),
        migrations.RenameField(
            model_name='msgraphcalendarscanner',
            old_name='grant_uuid',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='msgraphfilescanner',
            old_name='grant_uuid',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='msgraphmailscanner',
            old_name='grant_uuid',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='msgraphsharepointscanner',
            old_name='grant_uuid',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='msgraphteamsfilescanner',
            old_name='grant_uuid',
            new_name='graph_grant',
        ),
        migrations.RenameField(
            model_name='sbsysdbscanner',
            old_name='grant_uuid',
            new_name='grant',
        ),
    ]
