# Generated by Django 5.2.1 on 2025-08-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0020_grant_inherit_link'),
        ('os2datascanner', '0166_rename_ews_grant_uuid_exchangescanner_ews_grant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangescanner',
            name='ews_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.ewsgrant', verbose_name='EWS grant'),
        ),
        migrations.AlterField(
            model_name='exchangescanner',
            name='graph_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='filescanner',
            name='smb_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.smbgrant', verbose_name='SMB grant'),
        ),
        migrations.AlterField(
            model_name='gmailscanner',
            name='google_api_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.googleapigrant'),
        ),
        migrations.AlterField(
            model_name='googledrivescanner',
            name='google_api_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.googleapigrant'),
        ),
        migrations.AlterField(
            model_name='msgraphcalendarscanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='msgraphfilescanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='msgraphmailscanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='msgraphsharepointscanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='msgraphteamsfilescanner',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant'),
        ),
        migrations.AlterField(
            model_name='sbsysdbscanner',
            name='grant',
            field=models.ForeignKey(help_text='A service account with access to the SQL Server instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.smbgrant', verbose_name='Service account'),
        ),
    ]
