# Generated by Django 5.2.1 on 2025-09-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0020_grant_inherit_link'),
        ('os2datascanner', '0167_alter_exchangescanner_ews_grant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSharedDriveScanner',
            fields=[
                ('scanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.scanner')),
                ('google_admin_account', models.TextField(help_text='In order to scan shared drives an admin account for the scanned workspace is required.', verbose_name='Google Workspace Admin Email')),
                ('google_api_grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.googleapigrant')),
            ],
            options={
                'verbose_name': 'Google Shared Drive scanner',
            },
            bases=('os2datascanner.scanner',),
        ),
    ]
