# Generated by Django 5.2.1 on 2025-09-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0020_grant_inherit_link'),
        ('os2datascanner', '0167_alter_exchangescanner_ews_grant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphsharepointsite',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='MSGraph Grant'),
        ),
    ]
