# Generated by Django 5.2.1 on 2025-09-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0167_alter_exchangescanner_ews_grant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphsharepointscanner',
            name='scan_descriptions',
            field=models.BooleanField(default=False, verbose_name='scan list descriptions'),
        ),
    ]
