# Generated by Django 5.2.1 on 2025-09-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0063_grantextra'),
        ('os2datascanner', '0167_alter_exchangescanner_ews_grant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanner',
            old_name='org_unit',
            new_name='org_units',
        ),
        migrations.AlterField(
            model_name='rule',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scannerjobs', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='usererrorlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usererrorlogs', to='organizations.organization', verbose_name='organization'),
        ),
    ]
