# Generated by Django 5.2.1 on 2025-09-11 13:48

from django.db import migrations, models

from os2datascanner.utils.batch import BatchUpdate


def populate_raw_rule(apps, schema_editor):
    Rule = apps.get_model("os2datascanner", "Rule")
    CustomRule = apps.get_model("os2datascanner", "CustomRule")

    with BatchUpdate(Rule.objects, ["raw_rule"]) as batch:
        for obj in CustomRule.objects.iterator():
            r: Rule = obj.rule_ptr
            r.raw_rule = obj._rule
            batch.append(r)


def unpopulate_raw_rule(apps, schema_editor):
    Rule = apps.get_model("os2datascanner", "Rule")
    CustomRule = apps.get_model("os2datascanner", "CustomRule")

    with BatchUpdate(CustomRule.objects, ["_rule"]) as batch:
        for obj in CustomRule.objects.iterator():
            r: Rule = obj.rule_ptr
            obj._rule = r.raw_rule
            batch.append(obj)


def populate_categories(apps, schema_editor):
    CustomRule = apps.get_model("os2datascanner", "CustomRule")

    for obj in CustomRule.objects.iterator():
        obj.rule_ptr.categories.set(obj._categories.all())


def unpopulate_categories(apps, schema_editor):
    CustomRule = apps.get_model("os2datascanner", "CustomRule")

    for obj in CustomRule.objects.iterator():
        obj._categories.set(obj.rule_ptr.categories.all())


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0168_rename_org_unit_scanner_org_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customrule',
            old_name='categories',
            new_name='_categories',
        ),
        migrations.AlterField(
            model_name='customrule',
            name='_categories',
            field=models.ManyToManyField(related_name='crules', to='os2datascanner.rulecategory', verbose_name='categories'),
        ),

        migrations.AlterField(
            model_name='customrule',
            name='_rule',
            field=models.JSONField(blank=True, null=True, verbose_name='Rule'),
        ),

        migrations.AddField(
            model_name='rule',
            name='categories',
            field=models.ManyToManyField(related_name='rules', to='os2datascanner.rulecategory', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='rule',
            name='raw_rule',
            field=models.JSONField(blank=True, null=True, verbose_name='Rule'),
        ),

        migrations.RunPython(
            populate_raw_rule,
            reverse_code=unpopulate_raw_rule
        ),
        migrations.RunPython(
            populate_categories,
            reverse_code=unpopulate_categories
        ),

        migrations.RemoveField(
            model_name="customrule",
            name="_categories",
        ),
        migrations.RemoveField(
            model_name="customrule",
            name="_rule",
        ),
    ]
