# Generated by Django 5.2.1 on 2025-09-11 14:50

from django.db import migrations


def reestablish_cr_objects(apps, schema_editor):
    # The only subclass of Rule was CustomRule, and some of the code before
    # this migration expects CustomRule objects to exist for every Rule. So
    # let's make that happen
    Rule = apps.get_model("os2datascanner", "Rule")
    CustomRule = apps.get_model("os2datascanner", "CustomRule")

    for r in Rule.objects.values().iterator():
        # Just doing CustomRule.objects.create(pk=r.pk, rule_ptr=r) has the
        # unhelpful side effect of nulling out all the unspecified rows in the
        # Rule table
        CustomRule.objects.create(
                pk=r["id"], rule_ptr_id=r["id"], **r)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0065_alter_organization_system_rules'),
        ('os2datascanner', '0169_prep_for_rule_merge'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=reestablish_cr_objects
        ),
        migrations.DeleteModel(
            name='CustomRule',
        ),
    ]
