# Generated by Django 5.2.1 on 2025-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0170_delete_customrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphsharepointscanner',
            name='scan_descriptions',
            field=models.BooleanField(default=False, verbose_name='scan list descriptions'),
        ),
    ]
