# Generated by Django 5.2.1 on 2025-10-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0020_grant_inherit_link'),
        ('organizations', '0065_alter_organization_system_rules'),
        ('os2datascanner', '0172_googleshareddrivescanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphsharepointsite',
            name='graph_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='MSGraph Grant'),
        ),
        migrations.AddField(
            model_name='msgraphsharepointsite',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='msgraphsharepointsite',
            name='uuid',
            field=models.TextField(verbose_name='site id'),
        ),
        migrations.AddConstraint(
            model_name='msgraphsharepointsite',
            constraint=models.UniqueConstraint(fields=('uuid', 'organization'), name='unique_sp_site_organization'),
        ),
    ]
