# Generated by Django 5.2.1 on 2025-12-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0173_msgraphsharepointsite_graph_grant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SbsysScanner',
        ),
    ]
