# Generated by Django 5.2.1 on 2025-11-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0174_delete_sbsysscanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledcheckup',
            old_name='interested_before',
            new_name='interested_after',
        ),
    ]
