# Generated by Django 5.2.1 on 2026-01-20 08:16

from django.db import migrations, models


def move_rules_to_new_categories(apps, schema_editor):
    Rule = apps.get_model("os2datascanner", "Rule")
    RuleCategory = apps.get_model("os2datascanner", "RuleCategory")
    NewRuleCategory = apps.get_model("os2datascanner", "NewRuleCategory")
    for category in RuleCategory.objects.iterator():
        NewRuleCategory.objects.get_or_create(identifier=category.name)

    for rule in Rule.objects.iterator():
        category_identifiers = rule.categories.values_list("name", flat=True)
        rule.new_categories.set(NewRuleCategory.objects.filter(identifier__in=category_identifiers))


def move_rules_to_old_categories(apps, schema_editor):
    Rule = apps.get_model("os2datascanner", "Rule")
    RuleCategory = apps.get_model("os2datascanner", "RuleCategory")
    NewRuleCategory = apps.get_model("os2datascanner", "NewRuleCategory")
    for category in NewRuleCategory.objects.iterator():
        RuleCategory.objects.get_or_create(name=category.identifier)

    for rule in Rule.objects.iterator():
        category_identifiers = rule.new_categories.values_list("identifier", flat=True)
        rule.categories.set(RuleCategory.objects.filter(name__in=category_identifiers))


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0175_fix_ancient_typo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRuleCategory',
            fields=[
                ('identifier', models.CharField(choices=[('number_id', 'number ID'), ('names', 'names'), ('addresses', 'addresses'), ('sick_leave', 'sick leave'), ('danish', 'Danish')], max_length=256, primary_key=True, serialize=False, verbose_name='identifier')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='new_categories',
            field=models.ManyToManyField(related_name='rules', to='os2datascanner.newrulecategory', verbose_name='new_categories'),
        ),
        migrations.RunPython(move_rules_to_new_categories, move_rules_to_old_categories),
        migrations.RemoveField(
            model_name='rule',
            name='categories',
        ),
        migrations.DeleteModel(
            name='RuleCategory',
        ),
    ]
