# Generated by Django 5.2.1 on 2026-01-20 08:40

import django.db.models.deletion
from django.db import migrations, models


def move_to_intermediary_category_model(apps, schema_editor):
    Rule = apps.get_model("os2datascanner", "Rule")
    RuleCategory = apps.get_model("os2datascanner", "RuleCategory")
    NewRuleCategory = apps.get_model("os2datascanner", "NewRuleCategory")
    for category in RuleCategory.objects.iterator():
        NewRuleCategory.objects.get_or_create(identifier=category.identifier)

    for rule in Rule.objects.iterator():
        category_identifiers = rule.categories.values_list("identifier", flat=True)
        rule.new_categories.set(NewRuleCategory.objects.filter(identifier__in=category_identifiers))


def move_to_final_category_model(apps, schema_editor):
    Rule = apps.get_model("os2datascanner", "Rule")
    RuleCategory = apps.get_model("os2datascanner", "RuleCategory")
    NewRuleCategory = apps.get_model("os2datascanner", "NewRuleCategory")
    for category in NewRuleCategory.objects.iterator():
        RuleCategory.objects.get_or_create(identifier=category.identifier)

    for rule in Rule.objects.iterator():
        category_identifiers = rule.new_categories.values_list("identifier", flat=True)
        rule.categories.set(RuleCategory.objects.filter(identifier__in=category_identifiers))


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0068_account_distinguished_name'),
        ('os2datascanner', '0176_newrulecategory_rule_new_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('identifier', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='identifier')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='categories',
            field=models.ManyToManyField(related_name='rules', to='os2datascanner.rulecategory', verbose_name='kategorier'),
        ),
        migrations.RunPython(move_to_final_category_model, move_to_intermediary_category_model),
        migrations.RemoveField(
            model_name='rule',
            name='new_categories',
        ),
        migrations.DeleteModel(
            name='NewRuleCategory',
        ),
        # These fields are altered because we are no longer lazily evaluating translations in rules.py
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='navn'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='organizations.organization', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='raw_rule',
            field=models.JSONField(blank=True, null=True, verbose_name='Regel'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='sensitivity',
            field=models.IntegerField(choices=[(3, 'Critical'), (2, 'Problem'), (1, 'Warning'), (0, 'Notification')], default=2, verbose_name='følsomhed'),
        ),
    ]
