# Generated by Django 5.2.1 on 2026-02-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0177_rulecategory_remove_rule_new_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbsysdbscanner',
            options={'verbose_name': 'SBSYS scanner', 'verbose_name_plural': 'SBSYS scanners'},
        ),
    ]
