# Generated by Django 5.2.1 on 2026-02-17 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0178_alter_sbsysdbscanner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_hash', models.CharField(max_length=256, verbose_name='File hash')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='File size in bytes')),
                ('occurrences', models.IntegerField(default=2, verbose_name='Number of occurrences')),
                ('mime_type', models.CharField(max_length=256, verbose_name='MIME type')),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplication_stats', to='os2datascanner.scanstatus')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scan_status', 'object_hash'), name='unique_object_hash')],
            },
        ),
        migrations.CreateModel(
            name='HashCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_hash', models.CharField(max_length=256, verbose_name='File hash')),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_cache', to='os2datascanner.scanstatus')),
            ],
            options={
                'indexes': [models.Index(fields=['scan_status', 'object_hash'], name='os2datascan_scan_st_7b8f73_idx')],
                'constraints': [models.UniqueConstraint(fields=('scan_status', 'object_hash'), name='unique_object_hash_per_scan')],
            },
        ),
    ]
