# Generated by Django 5.2.1 on 2026-03-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0179_add_account_permissions_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='max_pdf_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The maximum size of PDF files to scan, in megabytes. Set to 0 for no limit.', null=True, verbose_name='maximum PDF size (MB)'),
        ),
    ]
