# Generated by Django 5.2.1 on 2026-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0179_add_account_permissions_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='conversion_queue_priority',
            field=models.IntegerField(default=1, verbose_name='conversion queue priority'),
        ),
    ]
