# Generated by Django 5.2.1 on 2026-03-20 11:43

import django.db.models.deletion
import os2datascanner.projects.admin.adminapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0021_graphgrant_contacts_graphgrant_last_email_date'),
        ('os2datascanner', '0180_scanner_max_pdf_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCalendarScanner',
            fields=[
                ('scanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.scanner')),
                ('mail_domain', models.CharField(max_length=2048, verbose_name='Domain')),
                ('userlist', models.FileField(blank=True, null=True, upload_to=os2datascanner.projects.admin.adminapp.utils.upload_path_exchange_users)),
                ('service_endpoint', models.URLField(blank=True, default='', max_length=256, verbose_name='Service endpoint')),
                ('scan_attachments', models.BooleanField(default=True, help_text='Scan attachments', verbose_name='Scan attachments')),
                ('ews_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.ewsgrant', verbose_name='EWS grant')),
                ('graph_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant', verbose_name='Graph grant')),
            ],
            options={
                'verbose_name': 'Exchange Calendar scanner',
            },
            bases=('os2datascanner.scanner',),
        ),
    ]
