# Generated by Django 5.2.1 on 2026-03-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0180_scanner_max_pdf_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_identifier', models.CharField(max_length=256, verbose_name='Unique Content Identifier')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='File size in bytes')),
                ('occurrences', models.PositiveIntegerField(default=2, verbose_name='Number of occurrences')),
                ('mime_type', models.CharField(max_length=256, verbose_name='MIME type')),
                ('process_time', models.DurationField(default=0, verbose_name='Total process time')),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplication_stats', to='os2datascanner.scanstatus')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scan_status', 'content_identifier', 'mime_type', 'file_size'), name='unique_object_hash')],
            },
        ),
        migrations.CreateModel(
            name='HashCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_identifier', models.CharField(max_length=256, verbose_name='Unique Content Identifier')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='File size in bytes')),
                ('mime_type', models.CharField(max_length=256, verbose_name='MIME type')),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_cache', to='os2datascanner.scanstatus')),
            ],
            options={
                'indexes': [models.Index(fields=['scan_status', 'content_identifier'], name='os2datascan_scan_st_508163_idx')],
                'constraints': [models.UniqueConstraint(fields=('scan_status', 'content_identifier', 'mime_type', 'file_size'), name='unique_object_hash_per_scan')],
            },
        ),
    ]
