# Generated by Django 5.2.1 on 2026-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0181_duplicationstat_hashcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='only_notify_remediators',
            field=models.BooleanField(default=False, verbose_name='only notify remediators'),
        ),
    ]
