# Generated by Django 5.2.1 on 2026-04-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0181_duplicationstat_hashcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbsysdbscanner',
            name='owner_field',
            field=models.CharField(choices=[('SID', 'SID'), ('upn', 'user principal name'), ('logon', 'Windows logon name')], default='upn', help_text='The user alias value to use to associate SBSYS cases with imported users.', verbose_name='Ownership field'),
        ),
    ]
