# Generated by Django 5.2.1 on 2026-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0183_scanner_only_notify_remediators'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='conversion_queue_tag',
            field=models.CharField(
                default='full', max_length=32,
                verbose_name='conversion queue tag'),
        ),
    ]