# Generated by Django 5.2.1 on 2026-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0184_add_conversion_queue_priority_to_scanstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='conversion_queue_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='conversion queue name'),
        ),
    ]
