# Generated by Django 5.2.1 on 2026-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0073_remove_organizationalunit_level_and_more'),
        ('os2datascanner', '0185_scanstatus_conversion_queue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='org_units',
            field=models.ManyToManyField(blank=True, related_name='scanners', to='organizations.organizationalunit', verbose_name='organizational unit'),
        ),
    ]
