# Generated by Django 5.2.1 on 2026-07-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0186_alter_scanner_org_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='sensitivity',
        ),
    ]
