# Generated by Django 5.2.1 on 2026-08-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0187_remove_rule_sensitivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererrorlog',
            name='checkup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usererrorlogs', to='os2datascanner.scheduledcheckup'),
        ),
    ]
