# Generated by Django 5.2.1 on 2026-08-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0188_usererrorlog_checkup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='exclusion_rule',
        ),
    ]
