# Generated by Django 5.2.1 on 2026-07-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0188_usererrorlog_checkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveredaccount',
            name='status_is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coveredaccount',
            name='message',
            field=models.TextField(blank=True, default=""),
        ),
    ]
