# Generated by Django 5.2.1 on 2026-06-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0189_remove_scanner_exclusion_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanner',
            old_name='max_pdf_size',
            new_name='max_file_size',
        ),
    ]
