# Generated by Django 5.2.1 on 2026-08-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0190_rename_max_pdf_size_scanner_max_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='max_file_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The maximum size of files to scan, in megabytes. Set to 0 for no limit. (Only works for files where size is available.)', null=True, verbose_name='maximum file size (MB)'),
        ),
    ]
