# Generated by Django 5.2.1 on 2026-08-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0191_alter_scanner_max_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbsysdbscanner',
            name='owner_field',
            field=models.CharField(choices=[('SID', 'SID'), ('upn', 'user principal name'), ('logon', 'Windows logon name')], default='upn', help_text='The database field to use to associate SBSYS cases with imported users.', verbose_name='Ownership field'),
        ),
    ]
