# Generated by Django 5.2.1 on 2026-06-22 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0192_sbsysdbscanner_owner_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveObjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=64)),
                ('object_path', models.TextField(blank=True)),
                ('current_path', models.TextField(blank=True)),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_objects', to='os2datascanner.scanstatus')),
            ],
            options={
                'ordering': ('pk',),
                'constraints': [models.UniqueConstraint(fields=('scan_status', 'object_key'), name='unique_active_object_per_scan')],
            },
        ),
    ]
