# Generated by Django 5.2.1 on 2026-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0194_activeobjectstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='only_notify_remediators',
            field=models.BooleanField(default=False, help_text="Results found by this scanner only go to users with the scanner's remediator role, and to universal remediators", verbose_name='only notify remediators'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='only_notify_superadmin',
            field=models.BooleanField(default=False, help_text='Results found by this scanner go to users with permission to view the "Withheld" tab in the Report Module, who can then delegate them to their owners.', verbose_name='only notify superadmin'),
        ),
    ]
