# Generated by Django 3.2.11 on 2025-01-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_backgroundjob__exec_state_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='conversion_delta_queue',
            field=models.TextField(default='os2ds_conversions'),
        ),
        migrations.AddField(
            model_name='client',
            name='conversion_full_queue',
            field=models.TextField(default='os2ds_conversions'),
        ),
        migrations.AddField(
            model_name='client',
            name='explorer_delta_queue',
            field=models.TextField(default='os2ds_scan_specs'),
        ),
        migrations.AddField(
            model_name='client',
            name='explorer_full_queue',
            field=models.TextField(default='os2ds_scan_specs'),
        ),
    ]
