# Generated by Django 4.0.10 on 2024-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_backgroundjob__exec_state_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='_exec_state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='waiting', max_length=30, verbose_name='execution state'),
        ),
    ]
