# Generated by Django 5.2.1 on 2026-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_backgroundjob__exec_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='_exec_state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('finished with warnings', 'Finished with warnings')], default='waiting', max_length=30, verbose_name='execution state'),
        ),
    ]
