# Generated by Django 5.2.1 on 2026-01-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_backgroundjob__exec_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='_exec_state',
            field=models.CharField(choices=[('waiting', 'Afventer'), ('running', 'Kører'), ('cancelling', 'Annullering i gang'), ('finished', 'Afsluttet'), ('cancelled', 'Annulleret'), ('failed', 'Fejlet'), ('finished with warnings', 'Afsluttet med advarsler')], default='waiting', max_length=30, verbose_name='execution state'),
        ),
    ]
