SECRET_KEY = "DUMMYKEY(for development)DUMMYKEY(for development)"
DECRYPTION_HEX = "4b8930847cba7196a46ede3456fe33df564427a30910dd1ef9bc805f26559aeb"

# [mode]
DEBUG = true

# [functionality]
EXCLUSION_RULES = true
ANALYSIS_PAGE = true

# [site]
# The URL of this site, used in links in emails and in the redirect URL for
# OAuth 2.0 services. (This value should end with a forward slash.)
SITE_URL = "http://localhost:8020/"
REPORT_URL = "http://localhost:8040/"
SESSION_COOKIE_NAME = "admin_sessionid"

# [keycloak]
KEYCLOAK_BASE_URL = "http://localkeycloak.os2datascanner:8090"
KEYCLOAK_ADMIN_SECRET = "thisIsNotASecret"

# [Prometheus pushgateway]
PUSHGATEWAY_HOST = "http://pushgateway:9091"

# [installation]
OPTIONAL_APPS = [
    'debug_toolbar',
]
OPTIONAL_MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# [msgraph]
MSGRAPH_APP_ID = ""
MSGRAPH_CLIENT_SECRET = ""

# [os2mo]
OS2MO_TOKEN_URL = "http://keycloak:8080/auth/realms/mo/protocol/openid-connect/token"  
OS2MO_ENDPOINT_URL = "http://mo/graphql/v2"
OS2MO_CLIENT_ID = ""
OS2MO_CLIENT_SECRET = ""

# [scans]
ENABLE_FILESCAN = true
ENABLE_WEBSCAN = true
ENABLE_EXCHANGESCAN = true
ENABLE_GOOGLEDRIVESCAN = true
ENABLE_GMAILSCAN = true
ENABLE_MSGRAPH_MAILSCAN = true
ENABLE_MSGRAPH_FILESCAN = true
ENABLE_MSGRAPH_CALENDARSCAN = true
ENABLE_SBSYSSCAN = true

# [email]
DEFAULT_FROM_EMAIL = "os2datascanner@magenta.dk"
ADMIN_EMAIL = "os2datascanner@magenta.dk"
EMAIL_HOST = 'mailhog'
EMAIL_PORT = 1025

# https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#debug-toolbar-config
[DEBUG_TOOLBAR_CONFIG]
SHOW_COLLAPSED = true
# by setting a callback function it is not needed to set @INTERNAL_IPS
SHOW_TOOLBAR_CALLBACK = "os2datascanner.projects.utils.debug.debug_toolbar_callback"

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "queue"
AMQP_USER = "os2ds"
AMQP_PWD = "os2ds"

[DATABASES]

    [DATABASES.default]
    ENGINE = "django_prometheus.db.backends.postgresql"
    NAME = "os2datascanner_admin"
    USER = "os2datascanner_admin_dev"
    PASSWORD = "os2datascanner_admin_dev"
    HOST = "db"
