SECRET_KEY = "DUMMYKEY(for development)DUMMYKEY(for development)"
DECRYPTION_HEX = "4b8930847cba7196a46ede3456fe33df564427a30910dd1ef9bc805f26559aeb"

# [mode]
DEBUG = true
# Used for filescan and mounting
PRODUCTION = false

# [site]
# The URL of this site, used in links in emails and in the redirect URL for
# OAuth 2.0 services. (This value should end with a forward slash.)
SITE_URL = "http://localhost:8020/"
ALLOWED_HOSTS = []
SESSION_COOKIE_NAME = "admin_sessionid"

# [keycloak]
KEYCLOAK_BASE_URL = "http://localkeycloak.os2datascanner:8090"
KEYCLOAK_ADMIN_CLIENT = "admin-cli"
KEYCLOAK_ADMIN_SECRET = "2757d2ba-d818-4b6a-b851-12d58a831f29"

# [installation]
OPTIONAL_APPS = [
    'django_extensions',
    'os2datascanner.projects.admin.core',
    'os2datascanner.projects.admin.organizations',
    'os2datascanner.projects.admin.import_services',
]

# [scans]
ENABLE_FILESCAN = true
ENABLE_WEBSCAN = true
ENABLE_EXCHANGESCAN = true
ENABLE_GOOGLEDRIVESCAN = true
ENABLE_GMAILSCAN = true
ENABLE_MSGRAPH_MAILSCAN = true
ENABLE_MSGRAPH_FILESCAN = true
ENABLE_SBSYSSCAN = true

# [email]
DEFAULT_FROM_EMAIL = "os2datascanner@magenta.dk"
ADMIN_EMAIL = "os2datascanner@magenta.dk"
EMAIL_HOST = "localhost"
EMAIL_PORT = 25

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "queue"
AMQP_USER = "os2ds"
AMQP_PWD = "os2ds"

[DATABASES]

    [DATABASES.default]
    ENGINE = "django.db.backends.postgresql_psycopg2"
    NAME = "os2datascanner_admin"
    USER = "os2datascanner_admin_dev"
    PASSWORD = "os2datascanner_admin_dev"
    HOST = "db"
