# Part of the OSdatascanner system, copyright © 2014-2026 Magenta ApS.
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, you can
# obtain one at http://mozilla.org/MPL/2.0/.

from django.db import models
from django.utils.translation import gettext_lazy as _

from .scanner_reference import ScannerReference


class LeaderStatisticSnapshot(models.Model):
    """A point-in-time snapshot of the aggregated leader-overview statistics for
    a single organization.

    The leader overview is served from the most recent snapshot instead of
    computing the (very expensive) per-account aggregates live on every page
    load. Snapshots are regenerated by the ``snapshot_leader_stats`` management
    command according to the organization's ``leader_snapshot_interval``."""

    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.CASCADE,
        related_name="leader_snapshots",
        verbose_name=_("organization"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name=_("created at"),
    )

    class Meta:
        get_latest_by = "created_at"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["organization", "-created_at"]),
        ]

    def __str__(self):
        return f"Leader snapshot for {self.organization} ({self.created_at})"


class AccountResultSnapshot(models.Model):
    """One row per (account, scanner_job, source_type) bucket within a snapshot.

    Each row holds the distinct-report sub-counts needed to rebuild every value
    shown on the leader overview under any scannerjob/source_type filter
    combination: filtered views sum the matching buckets per account, and
    ``handle_status`` and ``fp_ratio`` are recomputed from those sums."""

    snapshot = models.ForeignKey(
        LeaderStatisticSnapshot,
        on_delete=models.CASCADE,
        related_name="account_results",
    )
    account = models.ForeignKey(
        "organizations.Account",
        on_delete=models.CASCADE,
        related_name="+",
    )
    scanner_job = models.ForeignKey(
        ScannerReference,
        on_delete=models.CASCADE,
        related_name="+",
    )
    source_type = models.CharField(max_length=2000)

    # Unhandled, not withheld, not from a shared or remediator alias. Doubles as
    # the '_unhandled_count' used when deriving handle_status.
    unhandled_results = models.PositiveIntegerField(default=0)
    # As unhandled_results, but withheld (only_notify_superadmin=True).
    withheld_results = models.PositiveIntegerField(default=0)
    # As unhandled_results, but from a datasource older than the retention policy
    # (computed with the organization's retention_days at snapshot time).
    old_results = models.PositiveIntegerField(default=0)
    # Handled within the three-week window used by handle_status.
    handled_recent = models.PositiveIntegerField(default=0)
    # Created within the three-week window used by handle_status.
    new_recent = models.PositiveIntegerField(default=0)
    # All handled reports, for the false-positive ratio denominator.
    handled_total = models.PositiveIntegerField(default=0)
    # All false-positive reports, for the false-positive ratio numerator.
    fp_total = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=["snapshot", "account"]),
        ]

    def __str__(self):
        return (f"{self.account} / {self.scanner_job} / {self.source_type}: "
                f"{self.unhandled_results} unhandled")
