# A unique secret for this OS2datascanner engine installation, used in key
# derivation for cryptographic primitives
secret_value = ""

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "localhost"
AMQP_USER = ""
AMQP_PWD = ""
AMQP_SCHEME = "amqp"
AMQP_PORT = 5672
AMQP_HEARTBEAT = 6000
AMQP_VHOST = "/"
    [amqp.AMQP_BACKOFF_PARAMS]
    max_tries = 10
    ceiling = 7
    warn_after = 6
    fuzz = 0

[subprocess]
# The maximum runtime allowed for an external tool (in seconds)
timeout = 45

[pipeline]
# The maximum runtime (in seconds) allowed:
# * in the explorer stage, for a Source to produce a single Handle;
# * in the processor stage, for a single conversion operation; or
# * in the tagger stage, for a single metadata extraction
op_timeout = 60
# The number of times to try one of the above pipeline operations
op_tries = 2

[pipeline.matcher]
# The maximum number of match objects to return for each rule that matches
# (must be at least 1)
obj_limit = 10

[conversions.cache]
# The directory in which to store cached representations of objects, if
# applicable
directory = ""

[model.libreoffice]
# The size at which LibreOffice-generated HTML should be thrown away and
# replaced by a new plaintext conversion (in bytes)
size_threshold = 1048576

[model.http]
# The maximum number of outgoing HTTP requests an individual process can make
# every second
limit = 2
# timeout for requests (in seconds)
timeout = 45
# Maximum allowed depth of related links while crawling a domain
ttl = 25

[model.msgraph]
# The maximum number of items to retrieve in each API call to the server
page_size = 100

# The time to spend waiting for an API response to begin (in seconds)
timeout = 30
