# Should the system be a bit chattier and more tolerant of developer fiddling?
DEBUG = false

# A unique secret for this OS2datascanner engine installation, used in key
# derivation for cryptographic primitives
secret_value = ""

# [logging]
LOG_LEVEL = "INFO"

# Should engine2 attempt to translate its strings?
USE_I18N = true
# A list, in order of preference, of language identifiers to be given to the
# translation infrastructure. Specify an empty list to use the default
# gettext autodetection logic, although be warned that this may not make sense
# outside of interactive use
LANGUAGES = ["da"]

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "localhost"
AMQP_USER = ""
AMQP_PWD = ""
AMQP_SCHEME = "amqp"
AMQP_PORT = 5672
AMQP_HEARTBEAT = 6000
AMQP_VHOST = "/"
    [amqp.AMQP_BACKOFF_PARAMS]
    max_tries = 10
    ceiling = 7
    warn_after = 6
    fuzz = 0

[subprocess]
# The maximum runtime allowed for an external tool (in seconds)
timeout = 45
# The maximum runtime allowed for GhostScript to compress a pdf.
ghostscript_timeout = 500

[ghostscript]
# Whether or not to preprocess PDF files with Ghostscript
enabled = false
# Maximum allowed processing time for GhostScript in seconds.
timeout = 500
# The base set of PDF parameters to GhostScript (see its "VectorDevices.html"
# documentation for more options)
pdf_profile = "/default"
# The basic arguments to be given to the Ghostscript interpreter. Adjust these
# values at your own risk; OS2datascanner may take some of them for granted
_base_arguments = ["-sDEVICE=pdfwrite", "-dCompatibilityLevel=1.7", "-dNOPAUSE", "-dBATCH"]
# Extra arguments to be appended to the Ghostscript command line, if any
extra_args = []

[tesseract]
# Extra arguments to be added to the Tesseract command line, if any
# Disabling inverted search (white text on black) to improve speed
# as it's unlikely to be relevant anyway.
extra_args = ["-l", "dan+eng", "-c", "tessedit_do_invert=0"]

[pipeline]
# The maximum runtime (in seconds) allowed:
# * in the processor stage, for a single conversion operation; or
# * in the tagger stage, for a single metadata extraction
op_timeout = 60
# The number of times to try one of the above pipeline operations
op_tries = 2
# Extra modules to be imported as the pipeline starts up (useful for trying out
# _staging data sources, for example)
extra_modules = []

[pipeline.matcher]
# The maximum number of match objects to return for each rule that matches
# (must be at least 1)
obj_limit = 10

[conversions.cache]
# The directory in which to store cached representations of objects, if
# applicable
directory = ""

[model]
# The maximum nesting depth; after this point, Source.from_handle will return
# None
# (ten should be generous enough for any realistic situation -- for example, an
# image (1) on page 4 (2) of a PDF file (3) in a Zip file (4) attached (5) to
# an email (6) exported to an .eml file (7) and then forwarded as an attachment
# (8) in another email (9) would still pose no problems)
max_depth = 10

[model.libreoffice]
# The size at which LibreOffice-generated HTML should be thrown away and
# replaced by a new plaintext conversion (in bytes)
size_threshold = 1048576

# Note that these settings only affect WebSource/WebResource
[model.http]
# The maximum number of outgoing HTTP requests an individual process can make
# every second
limit = 2
# timeout for requests (in seconds)
timeout = 45
# Maximum allowed depth of related links while crawling a domain
ttl = 25

[model.msgraph]
# The maximum number of items to retrieve in each API call to the server
page_size = 100

# The time to spend waiting for an API response to begin (in seconds)
timeout = 30

[utils.oauth2]
# The number of seconds to wait for a client credentials response from an OAuth
# 2.0 token provider before concluding that something has gone wrong
cc_token_timeout = 180
