DEBUG = true

secret_value = "THIS VALUE IS NOT SECRET"
# [logging]
LOG_LEVEL = "DEBUG"

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "queue"
AMQP_USER = "os2ds"
AMQP_PWD = "os2ds"

# timeout for requests (in seconds)
timeout = 20
ttl = 25

[pipeline]
extra_modules = [".model._staging.sbsysdb"]
