# Generated by Django 3.2.11 on 2022-09-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alias_organizations_alias_account_unique_constraint_'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='delegate_all_message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Delegation message'),
        ),
        migrations.AddField(
            model_name='account',
            name='delegate_all_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_all_from', to='organizations.alias', verbose_name='Delegate all matches to'),
        ),
    ]
