# Generated by Django 3.2.11 on 2023-08-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_organization_leadertab_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='match_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='withheld_matches',
        ),
    ]
