# Generated by Django 3.2.11 on 2024-03-06 10:06

from django.db import migrations, models


def set_email_field(apps, schema_editor):
    Account = apps.get_model("organizations", "Account")

    for account in Account.objects.all():
        email_aliases = account.aliases.filter(_alias_type="email")
        email_alias = email_aliases.first()
        if email_alias:
            account.email = email_alias._value
        else:
            account.email = account.user.email if account.user else None
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0030_alias_organizations_universal_remediator_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email'),
        ),
        migrations.RunPython(
            set_email_field, reverse_code=migrations.RunPython.noop
        ),
    ]
