# Generated by Django 3.2.11 on 2024-02-16 12:19

from django.db import migrations, models

def migrate_org_outlook_settings(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')

    for organization in Organization.objects.all():
        if organization.msgraph_write_permissions in ("DEL", "ALL"):
            organization.outlook_delete_email_permission = True
        if organization.msgraph_write_permissions in ("CAT", "ALL"):
            # At this point in time, we cannot assume otherwise - this is status quo.
            organization.outlook_categorize_email_permission = "IND"

        # Save changes.
        organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_account_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='outlook_categorize_email_permission',
            field=models.CharField(choices=[('ORG', 'Enable automatic categorization for entire organization'), ('IND', 'Allow users to categorize emails'), ('NON', 'No categorization')], default='NON', help_text='configure whether OSdatascanner should create Outlook categories and categorize found matches, and decide whether you want to enforce this on an organizational level (all accounts) or leave it up to the individual.', max_length=3, verbose_name='Outlook category settings'),
        ),
        migrations.AddField(
            model_name='organization',
            name='outlook_delete_email_permission',
            field=models.BooleanField(default=False, verbose_name='allow deletion of emails directly'),
        ),
        migrations.RunPython(migrate_org_outlook_settings,
                             reverse_code=migrations.RunPython.noop),
    ]
