# Generated by Django 3.2.11 on 2024-02-21 12:53

from django.db import migrations, models
import django.db.models.deletion

def remove_account_less_setting_objects(apps, schema_editor):
    AccountOutlookSetting = apps.get_model('organizations', 'AccountOutlookSetting')

    AccountOutlookSetting.objects.filter(account__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_remove_organization_msgraph_write_permissions'),
    ]

    operations = [
        migrations.RunPython(remove_account_less_setting_objects,
                             reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='accountoutlooksetting',
            name='account_username',
        ),
        migrations.AlterField(
            model_name='accountoutlooksetting',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_settings', to='organizations.account'),
        ),
    ]
