# Generated by Django 3.2.11 on 2022-05-04 11:53

from django.db import migrations


class Migration(migrations.Migration):
    # See grants/migrations/0005_dummy_sync for more information about this
    # odd migration

    dependencies = [
        ("organizations", "0036_organization_email_header_banner"),
    ]

    operations = [
    ]
