# Generated by Django 3.2.11 on 2024-05-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0040_dummy_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='shared',
            field=models.BooleanField(default=False, help_text='The results related to the user through this alias is shared with other users. Matches associated through this alias will not be taken into account in user statistics.', verbose_name='shared'),
        ),
    ]
