# Generated by Django 3.2.11 on 2024-04-16 05:49

from django.db import migrations, models

def delete_categories_without_uuid(apps, schema_editor):
    OutlookCategory = apps.get_model('organizations', 'OutlookCategory')

    OutlookCategory.objects.filter(category_uuid__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0042_move_outlook_category_info_to_outlookcategory_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='outlookcategory',
            constraint=models.UniqueConstraint(fields=('name', 'account_outlook_setting'), name='outlook_category_label_type_name_and_outlook_setting_constraint'),
        ),
        # We are about to non-nullable a previously nullable field.
        # We delete all instances without uuids, since these are meaningless.
        migrations.RunPython(delete_categories_without_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='outlookcategory',
            name='category_uuid',
            field=models.CharField(max_length=36, verbose_name='category UUID'),
        ),
        migrations.AddConstraint(
            model_name='outlookcategory',
            constraint=models.UniqueConstraint(fields=('category_name', 'account_outlook_setting'), name='outlook_category_display_name_and_outlook_setting_constraint'),
        ),
    ]
