# Generated by Django 3.2.11 on 2024-10-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0047_alter_account_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='handled_matches',
        ),
        migrations.RemoveField(
            model_name='account',
            name='match_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='match_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='withheld_matches',
        ),
    ]
