# Generated by Django 3.2.11 on 2024-11-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0048_trigram_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='handled_matches',
        ),
        migrations.RemoveField(
            model_name='account',
            name='match_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='match_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='withheld_matches',
        ),
    ]
