# Generated by Django 3.2.11 on 2025-01-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0050_organizationalunit_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='retention_days',
            field=models.PositiveIntegerField(default=30, verbose_name='retention days'),
        ),
        migrations.AddField(
            model_name='organization',
            name='retention_policy',
            field=models.BooleanField(default=False, verbose_name='retention policy'),
        ),
    ]
