# Generated by Django 3.2.11 on 2025-03-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0053_account_org_unique_username_deferrable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='_alias_type',
            field=models.CharField(choices=[('SID', 'SID'), ('email', 'email'), ('remediator', 'remediator'), ('upn', 'user principal name'), ('generic', 'generic')], db_column='alias_type', db_index=True, max_length=32, verbose_name='alias type'),
        ),
    ]
