# Generated by Django 3.2.11 on 2025-03-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0053_alter_syncedpermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncedpermission',
            options={'permissions': [('very_important', 'A very important permission'), ('destroy_univserse', 'Allowed to destroy the universe'), ('universal_keys', 'Access to all Google infrastructure')]},
        ),
    ]
