# Generated by Django 3.2.11 on 2025-04-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0054_new_upn_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sbsystab_access',
            field=models.CharField(choices=[('N', 'Hidden for all'), ('P', 'Visible with permission'), ('A', 'Visible for all')], default='N', max_length=1, verbose_name='SBSYS tab access'),
        ),
    ]
