# Generated by Django 4.2.21 on 2025-06-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0058_alter_alias_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='prioritize_graphgrant',
            field=models.BooleanField(default=False, help_text='prioritize a GraphGrant over an EWSGrant for exampel when using Exchange online rather than Exchange on-prem', verbose_name='Prioritize GraphGrant'),
        ),
    ]
