# Generated by Django 5.2.1 on 2025-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0060_deletion_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='leadertab_config',
            field=models.CharField(choices=[('UNI', 'Only allow managers to see units they manage in the leader overview'), ('ACC', 'Only allow managers to see accounts they manage in the leader overview'), ('BOT', 'Allow managers to see both units and accounts they manage in the leader overview')], default='UNI', max_length=3, verbose_name='Leader tab configuration'),
        ),
    ]
