# Generated by Django 5.2.1 on 2025-08-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0062_alter_organization_exchange_delete_permission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncedpermission',
            options={'permissions': [('view_sbsys_tab', 'Can view the SBSYS tab in Report'), ('filter_scannerjob_leader_overview', 'Can filter by scannerjob in the leader overview')]},
        ),
    ]
