# Generated by Django 5.2.1 on 2025-10-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0063_alter_syncedpermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncedpermission',
            options={'permissions': [('view_sbsys_tab', 'Can view the SBSYS tab in Report'), ('filter_scannerjob_leader_overview', 'Can filter by scannerjob in the leader overview'), ('view_scannerjob_list', 'Can view the scannerjob list in the report module'), ('delete_documentreports', 'Can permanently delete reports in the report module')]},
        ),
    ]
