# Generated by Django 5.2.1 on 2026-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0067_welcome_logon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='leader_snapshot_interval',
            field=models.PositiveIntegerField(default=24, help_text='How many hours may pass before the leader statistics snapshot is regenerated. The leader overview is served from the most recent snapshot rather than computed live on every page load.', verbose_name='Leader statistics snapshot interval'),
        ),
    ]
