ALTER DATABASE [SbSysNetDrift]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE  IF EXISTS [SbSysNetDrift];
GO

ALTER DATABASE [SbSysNetDriftDokument0000]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE  IF EXISTS [SbSysNetDriftDokument0000];
GO
