version: '3.4'
services:
  requirements:
    build:
      context: ../
      dockerfile: ./dev-environment/Dockerfile
    command: >
      sh -c "set -ex &&
             pip-compile requirements-engine.in &&
             pip-compile requirements-admin.in &&
             pip-compile requirements-report.in &&
             pip-compile requirements-api.in &&
             pip-compile requirements-test.in &&
             pip-compile requirements-lint.in"

    volumes:
      - ../requirements/python-requirements:/requirements/python-requirements
