# Generated by Django 2.2.10 on 2021-03-02 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0022_documentreport_created_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasMatchRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner_report.EmailAlias')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='os2datascanner_report.DocumentReport')),
            ],
        ),
    ]
