# Generated by Django 2.2.10 on 2021-03-04 13:54

from django.db import migrations, models
import django.db.models.deletion
import os2datascanner.projects.report.reportapp.models.aliases.adsidalias_model


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0023_aliasmatchrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsidalias',
            name='value',
            field=models.CharField(max_length=192, null=True, validators=[os2datascanner.projects.report.reportapp.models.aliases.adsidalias_model.validate_sid], verbose_name='SID'),
        ),
        migrations.AddField(
            model_name='emailalias',
            name='value',
            field=models.EmailField(max_length=254, null=True, verbose_name='Mailadresse'),
        ),
        migrations.AddField(
            model_name='webdomainalias',
            name='value',
            field=models.TextField(null=True, verbose_name='Web-domænenavn'),
        ),
        migrations.AlterField(
            model_name='aliasmatchrelation',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner_report.Alias'),
        ),
        migrations.AlterField(
            model_name='aliasmatchrelation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner_report.DocumentReport'),
        ),
        migrations.AlterUniqueTogether(
            name='aliasmatchrelation',
            unique_together={('alias', 'match')},
        ),
    ]
