# Generated by Django 3.2.4 on 2021-09-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0032_alter_documentreport_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.JSONField()),
                ('matches', models.JSONField()),
                ('sensitivity', models.IntegerField(null=True, verbose_name='sensitivity')),
                ('probability', models.FloatField(null=True, verbose_name='probability')),
                ('rule_type', models.CharField(default='', max_length=256, verbose_name='rule type')),
                ('resolution_status', models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Edited'), (2, 'Moved'), (3, 'Removed'), (4, 'No action')], db_index=True, null=True, verbose_name='resolution status')),
                ('resolution_time', models.DateTimeField(blank=True, null=True, verbose_name='resolution time')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner_report.documentreport')),
            ],
            options={
                'ordering': ['-sensitivity', '-probability', 'rule_type', 'pk'],
            },
        ),
    ]
