# Generated by Django 3.2.11 on 2022-09-15 08:47

from django.db import migrations, models

def populate_doc_report_place(apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")

    for dr in DocumentReport.objects.iterator():
        try:
            dr.place = dr.matches.handle.presentation_place
            dr.save()
        except AttributeError:
            pass
            


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0058_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='place',
            field=models.CharField(default='', max_length=256, verbose_name='place'),
        ),
        migrations.RunPython(populate_doc_report_place, reverse_code=migrations.RunPython.noop),
    ]
