# Generated by Django 3.2.11 on 2022-09-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_email_notification_schedule'),
        ('os2datascanner_report', '0058_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delegate_all_message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Delegation message'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delegate_all_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_all_from', to='organizations.alias', verbose_name='Delegate all matches to'),
        ),
    ]
