# Generated by Django 3.2.11 on 2023-04-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0071_populate_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='only_notify_superadmin',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Underret kun superadmin'),
        ),
        migrations.AddIndex(
            model_name='documentreport',
            index=models.Index(condition=models.Q(('number_of_matches__gte', 1), ('resolution_status__isnull', True)), fields=['resolution_status', 'number_of_matches', 'only_notify_superadmin', 'organization', 'owner'], name='dr_unhandled_query'),
        ),
    ]
