# Generated by Django 3.2.11 on 2023-06-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0076_alias_creation_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='place',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='name'),
        ),
    ]
