# Generated by Django 3.2.11 on 2024-11-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0082_recrunch_ews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='resolution_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Edited'), (2, 'Journalized and deleted'), (3, 'Deleted'), (4, 'False positive')], db_index=True, null=True, verbose_name='resolution status'),
        ),
    ]
