# Generated by Django 3.2.11 on 2024-12-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0083_rename_resolution_choice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentreport',
            index=models.Index(fields=['datasource_last_modified'], name='source_age_idx'),
        ),
    ]
