# Generated by Django 3.2.11 on 2025-01-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0084_documentreport_withheld_results_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentreport',
            options={'ordering': ['-sensitivity', '-probability', 'pk'], 'permissions': [('see_withheld_documentreport', 'Can see withheld DocumentReports'), ('distribute_withheld_documentreport', 'Can distribute withheld DocumentReports to users'), ('see_user_result_origins', 'Can see scannerjobs related to user results')], 'verbose_name_plural': 'document reports'},
        ),
    ]
