# Generated by Django 5.2.1 on 2025-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0084_documentreport_withheld_results_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='resolution_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Edited'), (2, 'Journalized and deleted'), (3, 'Deleted'), (4, 'False positive'), (5, 'No longer relevant')], db_index=True, null=True, verbose_name='resolution status'),
        ),
    ]
