# Generated by Django 5.2.1 on 2025-08-12 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0061_organization_leadertab_config'),
        ('os2datascanner_report', '0087_populate_scannerreference'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentreport',
            name='unique_scanner_pk_and_path',
        ),
        migrations.RemoveField(
            model_name='documentreport',
            name='scanner_job_name',
        ),
        migrations.RemoveField(
            model_name='documentreport',
            name='scanner_job_pk',
        ),
        migrations.AddField(
            model_name='scannerreference',
            name='only_notify_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scannerreference',
            name='org_units',
            field=models.ManyToManyField(related_name='scanners', to='organizations.organizationalunit'),
        ),
        migrations.AddField(
            model_name='scannerreference',
            name='scan_entire_org',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='documentreport',
            constraint=models.UniqueConstraint(fields=('scanner_job', 'path'), name='unique_scanner_pk_and_path'),
        ),
    ]
