# Generated by Django 5.2.1 on 2025-08-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0062_alter_organization_exchange_delete_permission_and_more'),
        ('os2datascanner_report', '0089_clean_up_orphan_scanners_and_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentreport',
            name='organization',
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='scanner_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reports', to='os2datascanner_report.scannerreference'),
        ),
        migrations.AlterField(
            model_name='scannerreference',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanners', to='organizations.organization'),
        ),
    ]
