# Generated by Django 5.2.1 on 2025-08-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0062_alter_organization_exchange_delete_permission_and_more'),
        ('os2datascanner_report', '0090_remove_documentreport_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='last_opened_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time last opened'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='raw_matches',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='raw_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='raw_problem',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='raw_scan_tag',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scannerreference',
            name='org_units',
            field=models.ManyToManyField(blank=True, related_name='scanners', to='organizations.organizationalunit'),
        ),
    ]
