# Generated by Django 5.2.1 on 2025-09-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0091_alter_documentreport_last_opened_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentreport',
            old_name='alias_relation',
            new_name='alias_relations',
        ),
    ]
