# Generated by Django 5.2.1 on 2025-09-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0062_alter_organization_exchange_delete_permission_and_more'),
        ('os2datascanner_report', '0092_rename_alias_relation_documentreport_alias_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='alias_relations',
            field=models.ManyToManyField(blank=True, db_table='new_alias_relation', related_name='reports', to='organizations.alias', verbose_name='Alias relation'),
        ),
    ]
