# Generated by Django 5.2.1 on 2025-10-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0093_alter_documentreport_alias_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentreport',
            options={'ordering': ['-sensitivity', '-probability', 'pk'], 'verbose_name_plural': 'document reports'},
        ),
    ]
