# Generated by Django 5.2.1 on 2025-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0094_alter_documentreport_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentreport',
            name='name',
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='sort_key',
            field=models.CharField(db_index=True, default='', verbose_name='sort key'),
        ),
    ]
