# Generated by Django 5.2.1 on 2026-05-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0096_alter_documentreport_resolution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='only_notify_remediators',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
