# Generated by Django 5.2.1 on 2026-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0097_documentreport_only_notify_remediators'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='datasource_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
