# Generated by Django 5.2.1 on 2026-07-07 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0068_organization_leader_snapshot_interval'),
        ('os2datascanner_report', '0098_documentreport_datasource_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderStatisticSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_snapshots', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='AccountResultSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=2000)),
                ('unhandled_results', models.PositiveIntegerField(default=0)),
                ('withheld_results', models.PositiveIntegerField(default=0)),
                ('old_results', models.PositiveIntegerField(default=0)),
                ('handled_recent', models.PositiveIntegerField(default=0)),
                ('new_recent', models.PositiveIntegerField(default=0)),
                ('handled_total', models.PositiveIntegerField(default=0)),
                ('fp_total', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.account')),
                ('scanner_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='os2datascanner_report.scannerreference')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_results', to='os2datascanner_report.leaderstatisticsnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='leaderstatisticsnapshot',
            index=models.Index(fields=['organization', '-created_at'], name='os2datascan_organiz_b1f606_idx'),
        ),
        migrations.AddIndex(
            model_name='accountresultsnapshot',
            index=models.Index(fields=['snapshot', 'account'], name='os2datascan_snapsho_68510e_idx'),
        ),
    ]
