# Generated by Django 5.2.1 on 2026-07-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0099_leaderstatisticsnapshot_accountresultsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentreport',
            options={'ordering': ['-probability', 'pk'], 'verbose_name_plural': 'document reports'},
        ),
        migrations.RemoveField(
            model_name='documentreport',
            name='sensitivity',
        ),
    ]
