# Generated by Django 5.2.1 on 2026-09-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0100_alter_documentreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('source_type', models.CharField(db_index=True, max_length=2000)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('scanner_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_reports', to='os2datascanner_report.scannerreference')),
            ],
        ),
        migrations.AddField(
            model_name='documentreport',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reports', to='os2datascanner_report.containerreport'),
        ),
        migrations.AddConstraint(
            model_name='containerreport',
            constraint=models.UniqueConstraint(fields=('scanner_job', 'path'), name='unique_container_scanner_pk_and_path'),
        ),
    ]
