# SPDX-FileCopyrightText: 2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

# THIS FILE CONTAINS DEFAULT CONFIGURATION SETTINGS. DO NOT CHANGE!!!
# To change the configuration of a specific instance, go the user configuration
# file. For development, the user configuration file is found here:
# /dev-environment/dev-settings.toml

SECRET_KEY = ""
DECRYPTION_HEX = ""

# [mode]
DEBUG = false
PRODUCTION = false

# [site]
# The URL of this site, used in links in emails and in the redirect URL for
# OAuth 2.0 services. (This value should end with a forward slash.)
SITE_URL = "*"
SITE_ID = 1
ALLOWED_HOSTS = []
SESSION_COOKIE_NAME = "sessionid"

# [keycloak]
KEYCLOAK_BASE_URL = ""
KEYCLOAK_ADMIN_CLIENT = "os2datascanner-admin"
KEYCLOAK_ADMIN_SECRET = ""

# [msgraph]
# The GUID of the registered Azure application corresponding to this
# OS2datascanner installation, used when requesting Microsoft Graph access:
MSGRAPH_APP_ID = ""
# The client secret used to demonstrate to Microsoft Graph that this
# OS2datascanner installation corresponds to a registered Azure application
# (client private keys are not yet supported):
MSGRAPH_CLIENT_SECRET = ""

# [sbsys]
# Using oauth with grant type client_credentials.
# These settings must be provided to later retrieve a token
# to then make API calls.
SBSYS_CLIENT_ID = ""
SBSYS_CLIENT_SECRET = ""
SBSYS_TOKEN_URL = ""
# API url should be pasted ending with "api/"
SBSYS_API_URL = ""

# [test]
TEST_RUNNER = "xmlrunner.extra.djangotestrunner.XMLTestRunner"
TEST_OUTPUT_DESCRIPTIONS = true
TEST_OUTPUT_VERBOSE = true
# TEST_OUTPUT_FILE_NAME is set under dirs

# [installation]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'recurrence',
    'mptt',
]
OS2DATASCANNER_APPS = [
    'os2datascanner.projects.admin.adminapp',
    'os2datascanner.projects.admin.core',
    'os2datascanner.projects.admin.organizations',
    'os2datascanner.projects.admin.import_services',
]
OPTIONAL_APPS = []

AUTH_PROFILE_MODULE = "os2datascanner.projects.admin.adminapp.UserProfile"
WSGI_APPLICATION = "os2datascanner.projects.admin.wsgi.application"
ROOT_URLCONF = "os2datascanner.projects.admin.urls"
STATIC_URL = "/static/"
ICON_SPRITE_URL = "/static/src/svg/symbol-defs.svg"
LOGIN_REDIRECT_URL = "/"
NOTIFICATION_INSTITUTION = ""

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
]

# Add settings here to make them accessible from templates
SETTINGS_EXPORT = [
    'DEBUG',
    'ENABLE_FILESCAN',
    'ENABLE_EXCHANGESCAN',
    'ENABLE_WEBSCAN',
    'ENABLE_DROPBOXSCAN',
    'ENABLE_MSGRAPH_MAILSCAN',
    'ENABLE_MSGRAPH_FILESCAN',
    'ENABLE_GOOGLEDRIVESCAN',
    'ENABLE_GMAILSCAN',
    'ENABLE_SBSYSSCAN',
    'ICON_SPRITE_URL',
    'ESTIMATE_AFTER'
]

# [internationalization]
LANGUAGE_CODE = "da-dk"
# Paths relative to the project directory should start with "*" while
# absolute paths should start with "/"
_LOCALE_PATHS = [
    ["*", "src", "os2datascanner", "projects", "admin", "locale"],
]
_LANGUAGES = [
    ["da", "Danish"],
]
TIMEZONE = "Europe/Copenhagen"
USE_I18N = true
USE_L10N = true
USE_TZ = true
USE_THOUSAND_SEPARATOR = true

# [email]
DEFAULT_FROM_EMAIL = "(Magenta Info) info@magenta.dk"
ADMIN_EMAIL = "(Magenta Admin) info@magenta.dk"
EMAIL_HOST = "localhost"
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_USE_TLS = false
EMAIL_PORT = 25
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# [scans]
ENABLE_FILESCAN = false
ENABLE_WEBSCAN = false
ENABLE_EXCHANGESCAN = false
ENABLE_DROPBOXSCAN = false
ENABLE_MSGRAPH_MAILSCAN = false
ENABLE_MSGRAPH_FILESCAN = false
ENABLE_GOOGLEDRIVESCAN = false
ENABLE_GMAILSCAN = false
ENABLE_SBSYSSCAN = false

# [logging]
DJANGO_LOG_LEVEL = "INFO"

# These settings are Django-specific, and must be top level to get picked up
AMQP_PIPELINE_TARGET = "os2ds_scan_specs"
AMQP_CONVERSION_TARGET = "os2ds_conversions"
AMQP_EVENTS_TARGET = "os2ds_events"

# [storage]
# File storage class - default is regular file system storage
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
# Google Cloud Storage bucket name (for django-storages[google]), requires the above
# to be set to 'storages.backends.gcloud.GoogleCloudStorage'
# See https://django-storages.readthedocs.io/en/latest/backends/gcloud.html
GS_BUCKET_NAME = ""

# Don't estimate the duration of a scan until at least this fraction of it is
# complete; 0.0 means that estimates will immediately be given, and 1.0 means
# that they never will (early estimates are always less accurate)
ESTIMATE_AFTER = 0.05

[amqp]
# Nested amqp settings are picked up by the common amqp utility module
AMQP_HOST = "localhost"
AMQP_USER = ""
AMQP_PWD = ""
AMQP_SCHEME = "amqp"
AMQP_PORT = 5672
AMQP_VHOST = "/"
    [amqp.AMQP_BACKOFF_PARAMS]
    max_tries = 10
    ceiling = 7
    warn_after = 6
    fuzz = 0

[DATABASES]

    [DATABASES.default]
    ENGINE = "django.db.backends.postgresql_psycopg2"
    NAME = "os2datascanner_admin"
    USER = "os2datascanner_admin"
    PASSWORD = ""
    HOST = "127.0.0.1"

[DATABASE_POOL_ARGS]
max_overflow = 10
pool_size = 5
recycle = 300

[dirs]
# These are the settings for various directories.
# Paths relative to the project directory should start with "*" while
# absolute paths should start with "/"
BUILD_DIR = ["*", "build"]
VAR_DIR = ["*", "var"]
LOGS_DIR = ["*", "var", "logs"]
STATIC_ROOT = ["*", 'src', 'os2datascanner', 'projects', 'static', 'admin']
MEDIA_ROOT = ["*", "uploads", "admin"]
TEST_OUTPUT_FILE_NAME = ["*", "build", "test-results.xml"]
